### ISSUE TITLE
Performance Problem on a PC Laptop

### ISSUE THREAD

**Issue by apfanz** [VBA-tools/VBA-JSON#102]
Someone I know with a PC laptop is having a performance problem with this class.  Here's the code I'm using:

`Set json = JsonConverter.ParseJson(response)`

where response is in the attached file.  This guy says parsing the attached file is taking over 30 seconds.  It takes less than a second on my desktop computer though.  Does anyone have any ideas on what the issue could be?
[test.txt](https://github.com/VBA-tools/VBA-JSON/files/2099382/test.txt)

**Comment by timhall** [comment]
A recent Windows update caused a big slowdown, so that is most likely the issue. It was fixed very recently in v2.3.0, so try updating to that version. If that doesn’t work, please feel free to reopen the issue.
