### ISSUE TITLE
Very slow performance in 64-bit Office

### ISSUE THREAD

**Issue by mr2001** [VBA-tools/VBA-JSON#103]
Using latest VBA-JSON v2.2.4
After upgrading to 64-bit Office, ParseJson takes **minutes** to parse a JSON file compared to a couple of seconds in 32-bit Office.
Please advise.

**Comment by timhall** [comment]
Hi @mr2001 the latest release is v2.3.0 and it should fix this. The problem seems to be related to a recent Windows update and some native code that was previously used in VBA-JSON.

**Comment by marcortw** [comment]
@timhall thanks for making this lib and especially for keeping things up to date! I ran into the same performance problems and very glad to see that it's well maintained.
