### ISSUE TITLE
Getting key names 

### ISSUE THREAD

**Issue by pet2131** [VBA-tools/VBA-JSON#105]
Hello, I read the issue "how to get key names" but I couldn't convert the solution for my code. I need to get the names of the keys(er256f2d,5fb73sg,hrf5sd343,jd6452c) The problem is that they are random.

`[ {"id":"30","position":"0","pc":{"er256f2d":{"url":null, "size":"5"},"5fb73sg":{"url":null, "size":"2"} }, {"id":"32","position":"11","pc":{"hrf5sd343":{"url":null, "size":"12"},"jd6452c":{"url":null, "size":"4"} }  ]           `

**Comment by juhayes** [comment]
Quick glance:
Probably have to loop through each item - pull out and parse each "pc" item, and grab the keys from each secondary parsed element...

so:
``
Set Parse1 = JsonConverter.ParseJson(JsonText)
Dim Keys[] as string

For each item in Parse1
  Parse2 = JsonCOnverter.ParseJson(item("pc"))
  Keys.append(Parse2.Keys)
  Next item
``

**Comment by timhall** [comment]
Thanks for responding @juhayes, here's an alternative where you don't have to parse more than once:

```vb
Dim Values As Collection
Set Values = JsonConverter.ParseJson(Json)

Dim Value As Dictionary
Dim Id As Variant
Dim Ids As New Collection

For Each Value In Values
    For Each Id In Value("pc").Keys
        Ids.Add Id
    Next Id
Next Value
```
