### ISSUE TITLE
Can not load provided sample file, error "Error Parsing JSON: "col": sumnumber"

### ISSUE THREAD

**Issue by SynerSoft** [VBA-tools/VBA-JSON#125]
Provided sample code and file will not run.  Sad waste of time.

![image](https://user-images.githubusercontent.com/15149479/52439740-4b90b780-2aea-11e9-8e18-b8fc596deb6d.png)

**Comment by SynerSoft** [comment]
> Provided sample code and file will not run. Sad waste of time.
> 
> ![image](https://user-images.githubusercontent.com/15149479/52439740-4b90b780-2aea-11e9-8e18-b8fc596deb6d.png)

In order to run, the sumnumber in the sample .JSON file needs to be replaced with a number or placed in quotes.

**Comment by timhall** [comment]
What provided sample file?

**Comment by timhall** [comment]
Welcome to GitHub @SynerSoft we're generally a friendly bunch, you can try back tomorrow.

**Comment by SynerSoft** [comment]
My bad, the anomalous sample file was on another site that linked to this page.

Keep up the great work!
