### ISSUE TITLE
Run-time error '13': type mismatch

### ISSUE THREAD

**Issue by kimwalisch** [VBA-tools/VBA-JSON#126]
Hi,

I am trying to convert a json string into a dictionary using your library but unfortunately I get a ```Run-time error '13': type mismatch```:

My code looks like this:

```VB
Dim jsonStr As String
' jsonStr = "[ [ 1, "label1" ], [ 2, "label2" ] ]" 
jsonStr  = "[  [ 1, " + """" + "label1" + """" + " ], [ 2, " + """" + "label2" + """" + " ] ]" 

Dim Parsed As Dictionary
' Run-time error '13': type mismatch
Set Parsed = JsonConverter.ParseJson(jsonStr)
```

This my second day into Visual Basic so it is likely I am doing something silly...

**Comment by kimwalisch** [comment]
I have now succeeded in making it work using the json example string from your README.md:

```VB
Dim Json As Object
Set Json = JsonConverter.ParseJson("{""a"":1,""b"":2,""c"":3}")

For Each Value In Json.Items
    MsgBox ("Value: " + CStr(Value))
Next Value
``` 

But I still need to figure out how to parse an array of arrays json string like ```"[ [ 1, "label1" ], [ 2, "label2" ] ]"```.

**Comment by timhall** [comment]
When parsing an object use `Dictionary` and an array use `Collection`.

```vb
Dim Parsed As Collection
Set Parsed = JsonConverter.ParseJson("[[1, ""label1""], [2, ""label2""]]")

For Each Value In Parsed
  ' Note: Collections are 1-based
  Debug.Print Value(1) & ", " & Value(2)' -> "1, label1" or "2, label2"
Next Value
```

> This my second day into Visual Basic

Welcome!

**Comment by michelreyrolle** [comment]
@timhall 

Hello Tim, 
I installed your JSON converter and I am willing to use it to import git issues from a file in json format. The json file is generated using a curl command on a git repo. I checked the json file is correct (I am able to convert it with online tools, also I can manipulate it using JQ). However, my project needs to import issues into Excel so I am highly interested in your JSON converter :-)

Using your advanced example on my issues file, I get the same **type mismatch** error on the ParseJson statement. Any hint?

Oooops sorry. Using Collection instead of Dictionnary makes Parsing work perfectly. 

`Sub example2()
    Dim FSO As New FileSystemObject
    Dim JsonTS As TextStream
    Dim JsonText As String
    Dim Parsed As Dictionary
    
    ' Read .json file
    Set JsonTS = FSO.OpenTextFile("issues.json", ForReading)
    JsonText = JsonTS.ReadAll
    JsonTS.Close

    Debug.Print JsonText, Len(JsonText)
    
    ' Parse json to Dictionary
    ' "values" is parsed as Collection
    ' each item in "values" is parsed as Dictionary
    Set Parsed = JsonConverter.ParseJson(JsonText)`

**Comment by houghtonap** [comment]
Without seeing issues.json I suspect it's an array of objects, e.g., [ { ... }, { ... } ]. Therefore:

Dim Parsed as Collection

Set Parsed = JsonConverter.ParseJson(JsonText)

________________________________

**Comment by michelreyrolle** [comment]
@houghtonap Yep it works with collection.

Now I am looking at iterating issues in the collection and finds the following structure of the Parsed object. Now I need to figure out how to get jason values from this.

![image](https://user-images.githubusercontent.com/25659991/80834358-d7f83000-8bf0-11ea-853c-4f5923e9084f.png)

`Set Parsed = JsonConverter.ParseJson(JsonText)

 Debug.Print Parsed.Count

 Dim p, pp As Long

    For p = 1 To Parsed.Count

        Debug.Print Parsed(p).Count

        For pp = 1 To Parsed(p).Count

            Debug.Print Parsed(p).Item(pp)

        Next pp

    Next p``

**Comment by houghtonap** [comment]
You need to look at the Collection object and Dictionary object on Microsoft's website to determine what methods to use. I posted to someone else's issue that gave transversal code. See issue #131.

________________________________

**Comment by michelreyrolle** [comment]
> 
> You need to look at the Collection object and Dictionary object on Microsoft's website to determine what methods to use. I posted to someone else's issue that gave transversal code. See issue #131.
> […](#)

Before going further I would like to understand why the collection only shows item labels and no values (See watch window screenshot) above where values of items in the collection are only json labels. I am wondering if values were actually parsed. The structure of my json file is attached.
[sample-issues.zip](https://github.com/VBA-tools/VBA-JSON/files/4566145/sample-issues.zip)

**Comment by houghtonap** [comment]
The collection object is used to hold an array. Array items in JavaScript are numbered. Thus, the key in the Collection object is a number and the value is the JavaScript primitive, Array or Object. Therefore, given your JSON:

Dim Parsed as Collection
Dim Obj as Dictionary

Set Parsed = JsonConverter.ParseJson(JsonText)
Set Obj = Parsed(0)

Obj now contains the first JSON Object in the Array which becomes a Scripting.Dictionary object in VBA. You then need to use it's methods to access properties in the JSON Object.

Again I'll refer you to read the documentation on Microsoft's website to see what methods are available on both the Collection object and the Scripting.Dictionary object and to understand how they work.

See also the code in issue #131 in my posts.



________________________________

**Comment by michelreyrolle** [comment]
@houghtonap This was my first JSON parsing with VBA. I think I've now understood the mapping logic of JSON elements onto **Dictionnary** and **Collection** objects. Thanks again.

**Comment by nextjs-app-beta** [comment]
> When parsing an object use `Dictionary` and an array use `Collection`.
> 
> Dim Parsed As Collection
> Set Parsed = JsonConverter.ParseJson("[[1, ""label1""], [2, ""label2""]]")
> 
> For Each Value In Parsed
>   ' Note: Collections are 1-based
>   Debug.Print Value(1) & ", " & Value(2)' -> "1, label1" or "2, label2"
> Next Value
> > This my second day into Visual Basic
> 
> Welcome!





https://stackdev.space/questions/how-to-extract-data-from-a-collection-using-vba
