### ISSUE TITLE
Object Required - Runtime error 424

### ISSUE THREAD

**Issue by vince1393** [VBA-tools/VBA-JSON#127]
I keep getting an error in Excel 2013 with  the code below. Can't seem to figure out a solution, have tried several different solutions to no avail.

```
Sub Submit()
    Dim excelRange As Range
    Dim Entries As New Collection
    Dim Entry As New Dictionary
    Dim row As Long
    
    Set excelRange = Cells(1, 1).CurrentRegion
    
    For row = 2 To excelRange.Rows.Count
        Set Entry = New Dictionary
        Entry("stakeholder") = Cells(row, 1)
        Entry("subject") = Cells(row, 2)
        Entry("initialEngagement") = Cells(row, 3)
        Entry("type") = Cells(row, 4)
        Entry("frequency") = Cells(row, 5)
        Entry("startDate") = Cells(row, 6)
        Entry("EndDate") = Cells(row, 7)
    
        Entries.Add Entry
        
    Next row
    
    Dim Obj As New Dictionary
    Set Obj("entries") = Entries
    
    Debug.Print jsonConverter.ConvertToJson(Obj, Whitespace:=2)

End Sub
```

**Comment by vince1393** [comment]
Solved. Needed to add the .bas file to the VBA imports.

**Comment by JaroslawStormowski** [comment]
i think I have the same error, can you help me and tell me which .bas file did you added?

**Comment by vince1393** [comment]
> i think I have the same error, can you help me and tell me which .bas file did you added?

It's on the ReadMe, easy to miss near the bottom:

**Installation**
1. Download the latest release
2. Import JsonConverter.bas into your project (Open VBA Editor, Alt + F11; File > Import File)
3. Add Dictionary reference/class
For Windows-only, include a reference to "Microsoft Scripting Runtime"
For Windows and Mac, include VBA-Dictionary

**Comment by JaroslawStormowski** [comment]
Thanks :-)
