### ISSUE TITLE
How export data from Ms Access with VBA to Json

### ISSUE THREAD

**Issue by nectorprime** [VBA-tools/VBA-JSON#140]
I need help on how to serialize the data from MS Access VBA to Json , the data will be used by some other programs, and so Json is coming as way of provide a better data exchange property. I have installed Json Discretionary as part of Ms Access VBA project to help serialize/de-serialize the data.

 

For de-seliarize here is the code below:

Public Sub Example()
Dim JSONString As String
JSONString = "{""Name"":""Value""}"
Dim JSON As cJSON
Set JSON = New cJSON
Dim D As Dictionary
Set D = JSON.Deserialize(JSONString)
If (JSON.IsOk()) Then
MsgBox D.Item("Name")            'shows Value
Else
MsgBox JSON.ShowWhyNotOk()
End If
Set D = Nothing
Set JSON = Nothing
End Sub
 
The problem is how to do the same if I want to send the data to the requesting external program. I admit I'm still new to this forum and I have no experience in VBA/Json.
 
I want to exchange the following fields from Ms Access Tables (tblcustomerinvoice/tblInvoicedetails)
(1) Customer Name (String)
(2) Invoice number (Integer)
(3) Address (string)
(4) Quantities sold (Double)
(5) Selling Price as (Double)
(6) Total Value (Double)
 
 
Any idea here will be highly appreciated
 
Regard
Chris

**Comment by houghtonap** [comment]
1. Create an Access query with the fields you want
2. In VBA create a public sub
2a. Open recordset to query in (1)
2b. For each field write out JSON per JSON spec at JSON.org to text file
3. Run public sub which shows up under macros in the VBA window.

Get Outlook for Android

________________________________

**Comment by nectorprime** [comment]
This was answered Okay
