### ISSUE TITLE
Regional Date in VBA Json Conveter

### ISSUE THREAD

**Issue by nectorprime** [VBA-tools/VBA-JSON#143]
I have checked the code does not handle the regional from control system of my computer. Is there a way to change this nice converter to handle regional dates, surely this could be a good thing.

Regards

Chris

**Comment by nectorprime** [comment]
I have sorted out this one

**Comment by timhall** [comment]
@nectorprime Any info that you can share here that could help others with the same problem or that I could integrate into the library?

**Comment by nectorprime** [comment]
Dear Timhall

I have a challenge in using a "POST"method , kindly how you can help me correcting the error , the same VBA code works when using "GET method. The problem is on the get method,kindly shade light also on the issue of password & user name.

Here is the code below:

Private Sub CmdSales_Click()
  
'  Const SQL_SELECT As String = "SELECT * FROM Qry3;"
  
  Dim coll As VBA.Collection
  Dim dict As Scripting.Dictionary
  Dim db As DAO.Database
  Dim rs As DAO.Recordset
  Dim fld As DAO.Field
  Dim qdf As DAO.QueryDef
  Dim prm As DAO.Parameter
  Dim http As Object
  Set http = CreateObject("MSXML2.XMLHTTP")
  Set db = CurrentDb
  Set qdf = db.QueryDefs("Qry4")
  http.Open "POST", "http://jsonplaceholder.typicode.com/users/?id=" & Me.txtUserID, False
  http.send ConvertToJson(coll, Whitespace:=3)
Set JSON = ParseJson(http.responseText)
For Each prm In qdf.Parameters
    prm = Eval(prm.Name)
Next prm
Set rs = qdf.OpenRecordset()

Set qdf = Nothing
  Set coll = New VBA.Collection
'  Set db = CurrentDb
'  Set rs = db.OpenRecordset(SQL_SELECT, dbOpenSnapshot)
  If Not rs.BOF And Not rs.EOF Then
    Do While Not rs.EOF
      Set dict = New Scripting.Dictionary
      For Each fld In rs.Fields
        dict.Add fld.Name, rs.Fields(fld.Name).Value
      Next fld

      coll.Add dict
      rs.MoveNext
    Loop
  End If

  rs.Close
  Set fld = Nothing
  Set rs = Nothing
  Set db = Nothing
  Set dict = Nothing
  MsgBox "Post Sucess", vbOKOnly, "Audited by Chris Hankwembo"
  Set coll = Nothing
End Sub

**Comment by nectorprime** [comment]
It finally sorted out
