### ISSUE TITLE
Is conversion of "\n" to <CR><LF> intentional or a bug?

### ISSUE THREAD

**Issue by onetalltree** [VBA-tools/VBA-JSON#150]
In json_ParseString, a \n is converted to vbCrLf, not vbLF ... this causes extra line break characters to be inserted when round-tripping deserialization and serialization. This seems like a bug.

```
            Case "n"
                json_BufferAppend json_Buffer, vbCrLf, json_BufferPosition, json_BufferLength

```

**Comment by houghtonap** [comment]
The JSON standard is agnostic about line terminators. It considers line terminators white space. Thus an implementation can output different white space and still produce a conforming document. Thus, it's probably not a good idea to depend on your line terminators or other extraneous whitespace staying intact, as you have found, during a round trip operation.

Get Outlook for Android

________________________________

**Comment by onetalltree** [comment]
Thanks Andrew. After I posted the issue, I saw that this has been discussed previously. I ended up modifying my version of the JSON Converter code to suit my needs.
