### ISSUE TITLE
Installation HowTo?

### ISSUE THREAD

**Issue by metawops** [VBA-tools/VBA-JSON#17]
Because it's my first time using a 3rd party library (is it called "library" in VBA?) within a VBA project and because I'm using VBA very rarely I have **no** idea of how to use / import / install / setup this VBA-JSON project within my VBA project.
Here at work we are still at Excel 2007 (and Windows 7) and I don't have admin rights on my PC. What are the steps I have to take to include and use your project in my own?
It would be great if you could update the Readme file by adding some kind of "Installation" section ... :+1:

**Comment by timhall** [comment]
@metawops Thanks, I suppose some instructions would help :smile:

1. Download the [latest release](https://github.com/VBA-tools/VBA-JSON/releases)
2. Import `JsonConverter.bas` into your project (Open VBA Editor, `Alt + F11`; File > Import File)

I've added these instructions to the readme.
