### ISSUE TITLE
OpenTextFile Problem

### ISSUE THREAD

**Issue by Magicmercury** [VBA-tools/VBA-JSON#170]
I´ve trying to start a little bit testing but i have a big problem. I can´t read a file.

`Public Sub exceljson()
Dim FSO As New FileSystemObject
Dim JsonTS As TextStream
Dim JsonText As String
Dim Parsed As Dictionary

' Read .json file
Set JsonTS = FSO.OpenTextFile("example.json", ForReading)
JsonText = JsonTS.ReadAll
JsonTS.Close
End Sub`

I got the Error at the line Set JsonTS - Can´t find a file. But the file is in the same folder.

What did I wrong?

Thanks

**Comment by houghtonap** [comment]
You probably need to use the full path to the file.

________________________________

**Comment by Magicmercury** [comment]
Sorry...your are right, I make a huge mistake..
