### ISSUE TITLE
Getting "Run TIme Error 13: Type Mismatch" while parsing a JSON using JSONConverter

### ISSUE THREAD

**Issue by viveklabs** [VBA-tools/VBA-JSON#172]
**Software:** Microsoft Office 365

JSON:

{
	"expand": "schema,names",
	"startAt": 0,
	"maxResults": 1000,
	"total": 8,
	"issues": [{
		"expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
		"id": "10011",
		"self": "http://192.168.99.100:8080/rest/api/2/issue/10011",
		"key": "TES-12",
		"fields": {
			"issuetype": {},
			"components": [],
			"timespent": null,
			"customfield_10101": [
				"com.atlassian.greenhopper.service.sprint.Sprint@1d4aa0ee[id=2,rapidViewId=1,state=FUTURE,name=Facebook March 2020 Release,startDate=2020-05-30T20:22:00.000Z,endDate=2020-06-18T20:22:00.000Z,completeDate=<null>,activatedDate=<null>,sequence=2,goal=<null>]"
			],
			"customfield_10102": "TES-1"
		}
	}]
}

Code written to extract "customfield_10101" and store the values in String variable

Dim Json As Object
Set Json = JsonConverter.ParseJson(.responseText)
Dim tempName As Variant
tempName = Json("issues")(1)("fields")("customfield_10101")(1)

**Getting "Run Time Error 13" in last line of the code.** 

Please help in resolving this. I need this to be resolved ASAP. Looking forward for the help.

**Comment by aholden10** [comment]
Vivek - the "fields" in the JSON are inside an array so you need the additional (1) to address that:
tempName = Json("issues")(1)("fields")("customfield_10101")(1)
Hope that helps.


    On Saturday, June 13, 2020, 07:56:39 AM EDT, Vivek Prasad <notifications@github.com> wrote:  
 
 


Software: Microsoft Office 365

JSON:

{
"expand": "schema,names",
"startAt": 0,
"maxResults": 1000,
"total": 8,
"issues": [{
"expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
"id": "10011",
"self": "http://192.168.99.100:8080/rest/api/2/issue/10011",
"key": "TES-12",
"fields": {
"issuetype": {},
"components": [],
"timespent": null,
"customfield_10101": [
"com.atlassian.greenhopper.service.sprint.Sprint@1d4aa0ee[id=2,rapidViewId=1,state=FUTURE,name=Facebook March 2020 Release,startDate=2020-05-30T20:22:00.000Z,endDate=2020-06-18T20:22:00.000Z,completeDate=,activatedDate=,sequence=2,goal=]"
],
"customfield_10102": "TES-1"
}
}]
}

Code written to extract "customfield_10101" and store the values in String variable

Dim Json As Object
Set Json = JsonConverter.ParseJson(.responseText)
Dim tempName As Variant
tempName = Json("issues")("fields")("customfield_10101")(1)

Getting "Run Time Error 13" in last line of the code.

Please help in resolving this. I need this to be resolved ASAP. Looking forward for the help.

**Comment by viveklabs** [comment]
Thank you aholden10 for your suggestion, but the issue was with Response itself, which I was getiing from the API. Now it is resolved and above code is working flawlessly.
