### ISSUE TITLE
trying to parse but i get an error

### ISSUE THREAD

**Issue by pelos** [VBA-tools/VBA-JSON#18]
i am trying to parse a little test.  this is my code that I put in a button,  following this tutorial.

    Dim test As String
    test = "{""expand"": ""operations,editmeta,changelog,transitions,renderedFields"",""id"": ""288269"",""self"": ""https://mySite.com/rest/api/2/issue/288269"",""key"": ""JIT-151""}"

    Dim JSON As Object
    Set JSON = JsonConverter.ParseJson(test)

when I get to this part I get an error  Compile error: User-defined type not defined  and open the module JsonConverter    and highlight this line
Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary

I am skipping a step?   thanks =) have a great day.

**Comment by pelos** [comment]
I also try to use the code from the example:
```
    Dim Json As Object
    set Json = JsonConverter.ParseJson("{""a"":123,""b"":[1,2,3,4],""c"":{""d"":456}}")
    Debug.Print Json("a")
```
and send me to the same line of code =(

**Comment by timhall** [comment]
Hi @pelos, `Dictionary` is a dependency for VBA-JSON. Please see the following lines from the readme:

> - For Windows-only support, include a reference to "Microsoft Scripting Runtime"
- For Mac and Windows support, include [VBA-Dictionary](https://github.com/VBA-tools/VBA-Dictionary).

**Comment by pelos** [comment]
thanks,  I was in a haste reading  and thought that was just for mac  thanks,  now is working =)

**Comment by ngoduchau1985** [comment]
Hi,
I got trouble like you.
I did insert the file JsonConverer into my marcro.
Before it works well for my code.
But now, when i run it, it has error: run time error 10001, error parsing json: <html><head
expecting '{' or '['.

please someone help me to fix this

**Comment by bchaiyut** [comment]
In VBA  go to menu 
Tools > References > 
mark check [/] Microsoft Scripting Runtime 
(file: scrrun.dll)
