### ISSUE TITLE
Option for output formatting ?

### ISSUE THREAD

**Issue by Baccanno** [VBA-tools/VBA-JSON#19]
Hi,
Thanks very much for this work. Would there be an easy way to add auto formatting to the json output ?

Simple line returns would already be great

**Comment by timhall** [comment]
Hi @Baccanno thanks for the suggestion, I think this would be a great addition. I should get some time to work on this soon.

**Comment by timhall** [comment]
@Baccanno Thanks for the suggestion, I've finally had a chance to implement this in v2.2.0

```vb
' (from readme example)
Debug.Print JsonConverter.ConvertToJson(Json)
' -> "{"a":123,"b":[1,2,3,4],"c":{"d":456,"e":789}}"

Debug.Print JsonConverter.ConvertToJson(Json, Whitespace:=2)
' -> "{
'       "a": 123,
'       "b": [
'         1,
'         2,
'         3,
'         4
'       ],
'       "c": {
'         "d": 456,
'         "e": 789  
'       }
'     }"
```

`Whitespace` can either be the number of spaces per indentation or a string to use for indentation (e.g. `vbTab`)

**Comment by lwrbakro** [comment]
Thank you

**Comment by Baccanno** [comment]
Very great! Happy to hear that

2016-06-28 16:26 GMT+02:00 lwrbakro <notifications@github.com>:

> Thank you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VBA-tools/VBA-JSON/issues/19#issuecomment-229065606>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADfo0L5uj928c_ckrHooTpOZbp_YrKhEks5qQS8fgaJpZM4HWgi6>
> .
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com
