### ISSUE TITLE
Compile Error: A module is not a valid type

### ISSUE THREAD

**Issue by danfelt** [VBA-tools/VBA-JSON#198]
I've imported VBA-JSON-2.3.1 into Excel 2016 (64-bit) and when I compile my code, I get " Compile Error: A module is not a valid type " on the following line of code: " Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary "

I've added References to Microsoft Scripting Runtime and Microsoft Forms 2.0 Object Library. Any help, solutions or suggestions would be greatly appreciated!

**Comment by RayCulp** [comment]
I suspect that you have a module in the project called "Dictionary" in addition to the Dictionary class from Microsoft Scripting Runtime. If this is the case, you might try deleting or renaming the module.

**Comment by danfelt** [comment]
Thank you @RayCulp, that solved my issue!
