### ISSUE TITLE
parsing null

### ISSUE THREAD

**Issue by pelos** [VBA-tools/VBA-JSON#20]
inside excel i am looping a series of json strings. but some times one of the values will come with null instead a string. so i try to do some error recognition but i am not getting the right stuff.
i would like to get a list where the first item will be "Tool Training" and since null fail with Type Mismatch in the second, i am trying a try except or an on error like this.

I also try `Dim return_value as Variant`  but I still get the error 13 mismatch attribute since I guess is trying to return a string and null is a Boolean =(        any trick that I might use thanks, I appreciate the help =).

```VB.net
Dim return_value As String     
On Error GoTo 22

return_value = jstring("fields")("customfield_18711")("value")

22:
return_value = "empty"

Resume Next
```

should only use resume? with out the next? or i don't even use the resume at all?

this is how the json strings look like

```
{
  "expand": "operations,editmeta,changelog,transitions,renderedFields",
  "id": "452637",
  "self": "example.com/rest/api/2/issue/452637",
  "key": "MP-16098",
  "fields": {
    "summary": "my summary",
    "customfield_18711": {
      "self": "example.com/rest/api/2/customFieldOption/48120",
      "value": "Tool Training",
      "id": "48120"
    }
  }
}

{
  "expand": "operations,editmeta,changelog,transitions,renderedFields",
  "id": "452637",
  "self": "example.com/rest/api/2/issue/452637",
  "key": "MP-16098",
  "fields": {
    "summary": "my summary",
    "customfield_18711": {
      "self": "example.com/rest/api/2/customFieldOption/48120",
      "value": null,
      "id": "48120"
    }
  }
}
```

(added some formatting)

**Comment by timhall** [comment]
Hi @pelos for this a simple `If` statement should suffice:

```VB.net
Dim Value As Variant
Value = jstring("fields")("customfield_18711")("value")

Dim return_value As String
If Not IsNull(Value) Then
  return_value = Value
Else
  return_value = "empty"
End If
```
