### ISSUE TITLE
Generalize UTC tests for international dates

### ISSUE THREAD

**Issue by Tech997** [VBA-tools/VBA-JSON#21]
Hello,

there is a bug. Spec runner fails in ISO-8601 dates (Finnish locale).
![vba-json bug](https://cloud.githubusercontent.com/assets/17961566/13903922/d125f826-ee96-11e5-9f32-7cdd10b178ae.png)

**Comment by timhall** [comment]
Something strange going on here, I don't know why the output would be `123456789012345678901234567890`. Can you run the specs in [VBA-tools/VBA-UTC](https://github.com/VBA-tools/VBA-UTC)?

Also, in VBA-Web I test a [few regions](https://github.com/VBA-tools/VBA-Web/tree/master/specs/regions) (manually and only occasionally, unfortunately). What region would I use for Finnish locale?

**Comment by Tech997** [comment]
Hello,
 
region is 'Finland' in english version of OS or 'Suomi' in finnisg localized version of OS.
 
Tested this...
 
Codeline
LocalDate = DateValue("Jan. 2, 2003") + TimeValue("4:05:06 PM")
generates Type mismatch error 13.
changed to local Tammikuu which is january in finnish language
LocalDate = DateValue("Tam. 2, 2003") + TimeValue("4:05:06 PM")
is accepted as date (so no type mismatch error).
Debug.prints...
Debug.Print VBA.Format$(UtcDate, "yyyy-mm-ddTHH:mm:ss.000Z") -> 2003-01-02T14:05:06.000Z
Debug.Print Iso -> 2003-01-02T14:05:06.000Z
 
but then codeline
LocalDate = ParseIso(Iso)
causes type mismatch 13 error in ParseIso routine at 
 Case 2
            ParseIso = ParseIso + VBA.TimeSerial(VBA.CInt(utc_TimeParts(0)), VBA.CInt(utc_TimeParts(1)), VBA.CInt(utc_TimeParts(2)))
 
UtcConverter.ParseIso ISO 8601 parsing error for 2003-01-02T14:05:06.000Z: 10013 - ISO 8601 parsing error for 2003-01-02T14:05:06.000Z: 13 - Type mismatch
 
Regards
Benkku 
Date: Sun, 20 Mar 2016 14:38:49 -0700

**Comment by Tech997** [comment]
also month and date are mismatched in
Private Function utc_DateToSystemTime(utc_Value As Date) As utc_SYSTEMTIME
 
? utc_DateToSystemTime.utc_wMonth
 1 
? utc_DateToSystemTime.utc_wDay
 2 

Finnish locale has day before month fex. 'dd.mm.yyyy', so code breaks if date is 13 or more.
 
Regards
Benkku 
Date: Sun, 20 Mar 2016 14:38:49 -0700

**Comment by Tech997** [comment]
Sorry, ignore that
 
? utc_DateToSystemTime.utc_wMonth
 1 
? utc_DateToSystemTime.utc_wDay
 2 

these  are perfectly correct order.
 
However seconds part contain milliseconds, which breaks code.
 
Regards
Benkku
From: bengtij@hotmail.com
To: reply@reply.github.com
Subject: RE: [VBA-JSON] Bug  (#21)
Date: Mon, 21 Mar 2016 00:24:02 +0200




also month and date are mismatched in
Private Function utc_DateToSystemTime(utc_Value As Date) As utc_SYSTEMTIME
 
? utc_DateToSystemTime.utc_wMonth
 1 
? utc_DateToSystemTime.utc_wDay
 2 

Finnish locale has day before month fex. 'dd.mm.yyyy', so code breaks if date is 13 or more.
 
Regards
Benkku 
Date: Sun, 20 Mar 2016 14:38:49 -0700

**Comment by Tech997** [comment]
Here are attached Finnish locale settings.
 
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Control Panel\International]
"Locale"="0000040B"
"LocaleName"="fi-FI"
"s1159"=""
"s2359"=""
"sCountry"="Suomi"
"sCurrency"="€"
"sDate"="."
"sDecimal"=","
"sGrouping"="3;0"
"sLanguage"="FIN"
"sList"=";"
"sLongDate"="d. MMMM'ta 'yyyy"
"sMonDecimalSep"=","
"sMonGrouping"="3;0"
"sMonThousandSep"=" "
"sNativeDigits"="0123456789"
"sNegativeSign"="-"
"sPositiveSign"=""
"sShortDate"="d.M.yyyy"
"sThousand"=" "
"sTime"=":"
"sTimeFormat"="H:mm:ss"
"sShortTime"="H:mm"
"sYearMonth"="MMMM yyyy"
"iCalendarType"="1"
"iCountry"="358"
"iCurrDigits"="2"
"iCurrency"="3"
"iDate"="1"
"iDigits"="2"
"NumShape"="1"
"iFirstDayOfWeek"="0"
"iFirstWeekOfYear"="2"
"iLZero"="1"
"iMeasure"="0"
"iNegCurr"="8"
"iNegNumber"="1"
"iPaperSize"="9"
"iTime"="1"
"iTimePrefix"="0"
"iTLZero"="0"
[HKEY_CURRENT_USER\Control Panel\International\Geo]
"Nation"="77"

 
From: bengtij@hotmail.com
To: reply@reply.github.com
Subject: RE: [VBA-JSON] Bug  (#21)
Date: Mon, 21 Mar 2016 00:31:56 +0200




Sorry, ignore that
 
? utc_DateToSystemTime.utc_wMonth
 1 
? utc_DateToSystemTime.utc_wDay
 2 

these  are perfectly correct order.
 
However seconds part contain milliseconds, which breaks code.
 
Regards
Benkku
From: bengtij@hotmail.com
To: reply@reply.github.com
Subject: RE: [VBA-JSON] Bug  (#21)
Date: Mon, 21 Mar 2016 00:24:02 +0200




also month and date are mismatched in
Private Function utc_DateToSystemTime(utc_Value As Date) As utc_SYSTEMTIME
 
? utc_DateToSystemTime.utc_wMonth
 1 
? utc_DateToSystemTime.utc_wDay
 2 

Finnish locale has day before month fex. 'dd.mm.yyyy', so code breaks if date is 13 or more.
 
Regards
Benkku 
Date: Sun, 20 Mar 2016 14:38:49 -0700
