### ISSUE TITLE
Please help !!! problems with multiple JSON-VBA in MS Access 2019/365

### ISSUE THREAD

**Issue by rwiedemannn** [VBA-tools/VBA-JSON#227]
Hi,

I use MS ACCESS and simple responses work perfectly.

the VBA-JSON is a great tool, but actually i have a problem to parse items from following json response, if the JSON response is multi-level:

{"orderStatus":{"tourGuid":"fc8578f9-2c29-41d2-bbea-363070d33949","orderGuid":"7da1170f-36eb-4fd2-b3c8-4f1666bec0db","orderState":0,"tourArrival":"11:49","eta":null,"formdata":null,"guid":"02928fe7-a8ef-4cac-a7d8-6d5004fb8fa8"},"status":{"code":100,"description":null,"invalidItemKeys":null}}

Does anyone have a solution or suggestion for me?
I need the items "orderState" and "tourArrival".....

Many many thanks to the community here !
Best from Rene

**Comment by aholden10** [comment]
If you tell the group what you've already tried you will probably get a quicker and better reply!
In the meantime I believe this is the map of your JSON:
('orderStatus')('tourGuid') => 'fc8578f9-2c29-41d2-bbea-363070d33949'('orderStatus')('orderGuid') => '7da1170f-36eb-4fd2-b3c8-4f1666bec0db'('orderStatus')('orderState') => 0('orderStatus')('tourArrival') => '11:49'('orderStatus')('eta') => None('orderStatus')('formdata') => None('orderStatus')('guid') => '02928fe7-a8ef-4cac-a7d8-6d5004fb8fa8'('status')('code') => 100('status')('description') => None('status')('invalidItemKeys') => None


    On Tuesday, May 3, 2022, 07:59:31 AM EDT, rwiedemannn ***@***.***> wrote:  
 
 


Hi,

I use MS ACCESS and simple responses work perfectly.

the VBA-JSON is a great tool, but actually i have a problem to parse items from following json response, if the JSON response is multi-level:

{"orderStatus":{"tourGuid":"fc8578f9-2c29-41d2-bbea-363070d33949","orderGuid":"7da1170f-36eb-4fd2-b3c8-4f1666bec0db","orderState":0,"tourArrival":"11:49","eta":null,"formdata":null,"guid":"02928fe7-a8ef-4cac-a7d8-6d5004fb8fa8"},"status":{"code":100,"description":null,"invalidItemKeys":null}}

Does anyone have a solution or suggestion for me?
I need the items "orderState" and "tourArrival".....

Many many thanks to the community here !
Best from Rene

**Comment by rwiedemannn** [comment]
**Many thanks for the answer. I managed to do it myself today with this code and it works perfectly! Big thanks again!**

_Dim JsonORDERstatus As Dictionary
Set JsonORDERstatus = JsonConverter.ParseJson(requestStringORDER.ResponseText)

Me!Text13 = requestStringORDER.ResponseText
Me!FO_ARCH_ENDK_DDF_arrival = JsonORDERstatus("orderStatus")("tourArrival")
Me!FO_ARCH_ENDK_DDF_orderstatus = JsonORDERstatus("orderStatus")("orderState")
Me!FO_ARCH_ENDK_DDF_eta = JsonORDERstatus("orderStatus")("eta")
DoCmd.Save_

**Comment by rwiedemannn** [comment]
**Many thanks for the answer. I managed to do it myself today with this code and it works perfectly! Big thanks again!**

_Dim JsonORDERstatus As Dictionary
Set JsonORDERstatus = JsonConverter.ParseJson(requestStringORDER.ResponseText)

Me!Text13 = requestStringORDER.ResponseText
Me!FO_ARCH_ENDK_DDF_arrival = JsonORDERstatus("orderStatus")("tourArrival")
Me!FO_ARCH_ENDK_DDF_orderstatus = JsonORDERstatus("orderStatus")("orderState")
Me!FO_ARCH_ENDK_DDF_eta = JsonORDERstatus("orderStatus")("eta")
DoCmd.Save_

**Comment by aholden10** [comment]
Excellent, glad you got to the answer yourself!


    On Wednesday, May 4, 2022, 10:34:16 AM EDT, rwiedemannn ***@***.***> wrote:  
 
 


Many thanks for the answer. I managed to do it myself today with this code and it works perfectly! Big thanks again!

_Dim JsonORDERstatus As Dictionary
Set JsonORDERstatus = JsonConverter.ParseJson(requestStringORDER.ResponseText)

Me!Text13 = requestStringORDER.ResponseText
Me!FO_ARCH_ENDK_DDF_arrival = JsonORDERstatus("orderStatus")("tourArrival")
Me!FO_ARCH_ENDK_DDF_orderstatus = JsonORDERstatus("orderStatus")("orderState")
Me!FO_ARCH_ENDK_DDF_eta = JsonORDERstatus("orderStatus")("eta")
DoCmd.Save_
