### ISSUE TITLE
Runtime Error '100001'

### ISSUE THREAD

**Issue by tduc0504** [VBA-tools/VBA-JSON#229]
Hi guys,

I have the json text as below

```
 { 
   "code": "INVALID",
   "message": "The 'gender' must be in range ["01", "02"]."
 }
```

when i parse to JSON i get the error as below
<img width="363" alt="image" src="https://user-images.githubusercontent.com/35360845/170997538-fbdd8b26-127c-4d09-b29b-f0f5eb696540.png">

Is there a way to get the entire message content?

Thank & best regards,

**Comment by Deedolith** [comment]
Start with valid JSON.
The double quotes surrounding 01 and 02 must be escaped.
