### ISSUE TITLE
Compile error: user-defined type not defined

### ISSUE THREAD

**Issue by MikeS2058** [VBA-tools/VBA-JSON#23]
After importing the JsonConverter into the VBA editor for Access 2013 and then doing a simple cut and past of the example code in the click event of a button, I get the following error: 
Compile error: user-defined type not defined
in the function: 
Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary

What am I doing wrong?

Just figured it out: I needed to add a reference to Microsoft Scripting Runtime.

**Comment by timhall** [comment]
@MikeS2058 Thanks for raising this issue, I've added a line to the installation instructions covering this.

**Comment by BeldarGH** [comment]
Hi, you have to add this VBA Reference in Tools -> References: "Microsoft Scripting Runtime"
Check you have this reference active.
Regards
