### ISSUE TITLE
Need Help - If Property doesn't exist

### ISSUE THREAD

**Issue by obie7712** [VBA-tools/VBA-JSON#240]
Hi,
my JSON structure is like this:

Json("tickets")(1)
Json("tickets")(2)
etc..

Some "Tickets" have:
Json("tickets")(1)("tags")
but not all

in VBA, how can i ignore the "tickets" that don't have tag ?

I tried this but it errors with object required
Json.Exists("tickets")(1)("tags")

**Comment by Nick-vanGemeren** [comment]
Don't use complex one-liners.

Try something like:
```
    Dim ticket As Dictionary
    For Each ticket In Json("tickets")
        If ticket.Exists("tags") Then ProcessTags ticket("tags")
      Next
```
Remember to make a reference to Microsoft Scripting Runtime.

If that solves your problem, please close the issue. If not, explain further and maybe attach a file of JSON input.

**Comment by obie7712** [comment]
> For Each ticket In Json("tickets")
>         If ticket.Exists("tags") Then ProcessTags ticket("tags")
>       Next

Thank you, that has worked :)
