### ISSUE TITLE
Wrong number of arguments or invalid property assignments 

### ISSUE THREAD

**Issue by SAMmsk2** [VBA-tools/VBA-JSON#242]
I have a JSON-document. I am trying to parse it and facing an issue of wrong number of arguments...

![image](https://user-images.githubusercontent.com/118157547/201591658-fc276f6a-7369-4aae-aa4c-e8d240f64076.png)

When I am watching the expression, I can see the value:

![image](https://user-images.githubusercontent.com/118157547/201591920-da7ffd5c-b472-4248-9caa-8eb81fef0538.png)

but when I am trying to put this value into the cell, I am facing the issue of the wrong number of arguments...

JSON-document is as follows:

![image](https://user-images.githubusercontent.com/118157547/201592151-031f3b60-2910-4acc-9b1f-ef750ff2bec7.png)

**Comment by aholden10** [comment]
It would be helpful to have some of your (anonymized) JSON data included as text to test - including its entire structure from the top. 
It's difficult for me to simply look at a picture of a snippet of the data and troubleshoot it! 
    On Monday, November 14, 2022 at 01:40:05 AM EST, SAMmsk2 ***@***.***> wrote:  
 
 


I have a JSON-document. I am trying to parse it and facing an issue of wrong number of arguments...



When I am watching the expression, I can see the value:



but when I am trying to put this value into the cell, I am facing the issue of the wrong number of arguments...

JSON-document is as follows:

**Comment by SAMmsk2** [comment]
[{"self":"https://api.tracker.yandex.net/v2/issues/ORG-14","id":"63723e421abdaf3f75b0c911","key":"ORG-14","version":1,"summary":"Запрос маркетинг","statusStartTime":"2022-11-14T13:10:26.231+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/1","id":"1","display":"Processor"},{"self":"https://api.tracker.yandex.net/v2/components/2","id":"2","display":"Radar"},{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"},{"self":"https://api.tracker.yandex.net/v2/components/4","id":"4","display":"Reserv"}],"updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"sla":[{"id":"63723e421abdaf3f75b0c910","settingsId":1,"clockStatus":"STARTED","violationStatus":"NOT_VIOLATED","warnThreshold":32400000,"failedThreshold":64800000,"warnAt":"2022-11-15T13:10:26.114+0000","failAt":"2022-11-16T13:10:26.114+0000","startedAt":"2022-11-14T13:10:26.114+0000","pausedAt":null,"stoppedAt":null,"pausedDuration":0,"toFailTimeWorkDuration":null,"spent":null,"previousSLAs":[],"startShiftedByPause":"2022-11-14T13:10:26.113+0000"}],"description":"Пришлите материалы по айсоурс","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdAt":"2022-11-14T13:10:26.114+0000","tipZadac":["Техподдержка по продуктам"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"telefon":"+79858302222","kontaktnoeLico":"Иванов Петр","votes":0,"commentWithExternalMessageCount":0,"kanalObrasenia":["Звонок"],"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"email":"sammsk@mail.ru","updatedAt":"2022-11-14T13:10:26.114+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-13","id":"63723dfafa9bf419a6baa14e","key":"ORG-13","version":1,"summary":"Не открывается чек лист в Инспекторе","statusStartTime":"2022-11-14T13:09:14.560+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"}],"updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"sla":[{"id":"63723dfafa9bf419a6baa14d","settingsId":1,"clockStatus":"STARTED","violationStatus":"NOT_VIOLATED","warnThreshold":32400000,"failedThreshold":64800000,"warnAt":"2022-11-15T13:09:14.501+0000","failAt":"2022-11-16T13:09:14.501+0000","startedAt":"2022-11-14T13:09:14.501+0000","pausedAt":null,"stoppedAt":null,"pausedDuration":0,"toFailTimeWorkDuration":null,"spent":null,"previousSLAs":[],"startShiftedByPause":"2022-11-14T13:09:14.500+0000"}],"description":"Чек лист по договору","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdAt":"2022-11-14T13:09:14.501+0000","tipZadac":["Техподдержка по продуктам"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"telefon":"+79858302222","kontaktnoeLico":"Иванов Петр","votes":0,"commentWithExternalMessageCount":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"kanalObrasenia":["E mail"],"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"email":"sammsk@mail.ru","updatedAt":"2022-11-14T13:09:14.501+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-12","id":"63723d91fa9bf419a6baa143","key":"ORG-12","version":1,"summary":"Добавить организацию в Инспектор","statusStartTime":"2022-11-14T13:07:28.932+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"}],"updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"sla":[{"id":"63723d90fa9bf419a6baa142","settingsId":1,"clockStatus":"STARTED","violationStatus":"NOT_VIOLATED","warnThreshold":32400000,"failedThreshold":64800000,"warnAt":"2022-11-15T13:07:28.879+0000","failAt":"2022-11-16T13:07:28.879+0000","startedAt":"2022-11-14T13:07:28.879+0000","pausedAt":null,"stoppedAt":null,"pausedDuration":0,"toFailTimeWorkDuration":null,"spent":null,"previousSLAs":[],"startShiftedByPause":"2022-11-14T13:07:28.878+0000"}],"description":"","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdAt":"2022-11-14T13:07:28.879+0000","tipZadac":["Техподдержка по продуктам"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"telefon":"+79858302222","kontaktnoeLico":"Семенов Ал","votes":0,"commentWithExternalMessageCount":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"email":"sammsk@mail.ru","updatedAt":"2022-11-14T13:07:28.879+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-5","id":"6357b4801bce432da5b2344d","key":"ORG-5","version":8,"statusStartTime":"2022-11-14T13:03:26.630+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/4","id":"4","display":"Reserv"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"При выборе поставщика не проставляются цены","linia":"2 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"previousStatusLastAssignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"createdAt":"2022-10-25T10:03:44.082+0000","tipZadac":["Техподдержка по продуктам"],"commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"updatedAt":"2022-11-14T13:03:26.630+0000","lastCommentUpdatedAt":"2022-10-26T11:43:47.417+0000","summary":"Ошибка в резерве","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.636+0000","start":"2022-10-25","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"followers":[{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"}],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":2,"votes":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-2","id":"635287147717186b17f26c1f","key":"ORG-2","version":7,"statusStartTime":"2022-11-14T13:03:26.553+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/2","id":"2","display":"Radar"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Добавить пользователя в радар Семенов АМИванов+7985800000","linia":"3 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-21T11:48:36.464+0000","tipZadac":["Техподдержка по продуктам"],"commentWithExternalMessageCount":0,"kanalObrasenia":["E mail"],"updatedAt":"2022-11-14T13:03:26.553+0000","summary":"Добавить пользователя","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.563+0000","start":"2022-10-25","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/2","id":"2","key":"minor","display":"Низкий"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"unique":"FORMS/0/115118782","votes":0,"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/3","id":"3","key":"inProgress","display":"В работе"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-9","id":"635b9401e94c9e4ed6e0ec7d","key":"ORG-9","version":5,"statusStartTime":"2022-11-14T13:03:26.479+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Добавить дост","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"previousStatusLastAssignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"createdAt":"2022-10-28T08:34:09.511+0000","tipZadac":["Прочее"],"telefon":"+79858302222","kontaktnoeLico":"Иванов","commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"updatedAt":"2022-11-14T13:03:26.479+0000","summary":"Предоставить доступ к решению","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.488+0000","start":"2022-10-28","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-8","id":"63592368616e64127b6bf90d","key":"ORG-8","version":5,"summary":"Добавить пользователя","statusStartTime":"2022-11-14T13:03:26.402+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"}],"updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.410+0000","resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"start":"2022-10-26","description":"Семенов ","linia":"2 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/2","id":"2","key":"minor","display":"Низкий"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-26T12:09:12.514+0000","tipZadac":["Прочее"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"commentWithExternalMessageCount":0,"kanalObrasenia":["Звонок"],"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"updatedAt":"2022-11-14T13:03:26.402+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-1","id":"635277028564d579ee86d930","key":"ORG-1","version":12,"statusStartTime":"2022-11-14T13:03:26.310+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/2","id":"2","display":"Radar"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"project":{"self":"https://api.tracker.yandex.net/v2/projects/2","id":"2","display":"Поддержка"},"description":"Тестовая задача","boards":[{"id":3,"name":"Доска проекта Поддержка"}],"linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-21T10:40:01.704+0000","tipZadac":["Маркетинг"],"commentWithExternalMessageCount":0,"kanalObrasenia":["Звонок"],"updatedAt":"2022-11-14T13:03:26.310+0000","summary":"тест","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.318+0000","start":"2022-10-24","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"followers":[{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"}],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-3","id":"635287db8564d579ee86da8c","key":"ORG-3","version":9,"statusStartTime":"2022-11-14T13:03:26.233+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/1","id":"1","display":"Processor"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Ошибка с интерфейсом в инспектореСеменов АМ+7985800000","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"previousStatusLastAssignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"createdAt":"2022-10-21T11:51:55.776+0000","tipZadac":["Техподдержка по продуктам"],"end":"2022-10-27","commentWithExternalMessageCount":0,"kanalObrasenia":["E mail"],"updatedAt":"2022-11-14T13:03:26.233+0000","summary":"Исправить ошибку в процессоре","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.238+0000","start":"2022-10-21","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"unique":"FORMS/0/115120566","votes":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-7","id":"63591b04510c046cda764b71","key":"ORG-7","version":5,"summary":"добавить пользователя","statusStartTime":"2022-11-14T13:03:26.147+0000","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:26.159+0000","resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Логтн Сеенов","linia":"2 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-26T11:33:24.686+0000","tipZadac":["Маркетинг"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"updatedAt":"2022-11-14T13:03:26.146+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-11","id":"635bb4adf7d5b15fdd4f598b","key":"ORG-11","version":5,"statusStartTime":"2022-11-14T13:03:25.950+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/3","id":"3","display":"Inspector"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Создать аккаунт","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-28T10:53:33.573+0000","tipZadac":["Техподдержка по продуктам"],"telefon":"+79858302222","kontaktnoeLico":"Иванов Петр","commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"email":"sammsk@mail.ru","updatedAt":"2022-11-14T13:03:25.950+0000","summary":"Создание доп аккаунта","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-11-14T13:03:25.955+0000","sla":[{"id":"635bb4adf7d5b15fdd4f5986","settingsId":1,"clockStatus":"STOPPED","violationStatus":"FAIL_CONDITIONS_VIOLATED","warnThreshold":32400000,"failedThreshold":64800000,"warnAt":"2022-10-31T10:53:33.573+0000","failAt":"2022-11-01T10:53:33.573+0000","startedAt":"2022-10-28T10:53:33.573+0000","pausedAt":null,"stoppedAt":"2022-11-01T07:03:25.950+0000","pausedDuration":0,"toFailTimeWorkDuration":null,"spent":331792377,"previousSLAs":[],"startShiftedByPause":"2022-10-28T10:53:33.572+0000"}],"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-10","id":"635bab29f7d5b15fdd4f586e","key":"ORG-10","version":3,"statusStartTime":"2022-10-28T10:14:07.980+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/2","id":"2","display":"Radar"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"ООО “Нефтянка”","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-28T10:12:57.086+0000","tipZadac":["Техподдержка по продуктам"],"telefon":"+79858302222","kontaktnoeLico":"Иванов Петр","end":"2022-10-28","commentWithExternalMessageCount":0,"email":"sammsk@mail.ru","updatedAt":"2022-10-28T10:14:07.975+0000","summary":"Выполнить настройки нового юрлица в Радаре","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-10-28T10:14:07.988+0000","start":"2022-10-28","sla":[{"id":"635bab29f7d5b15fdd4f586d","settingsId":1,"clockStatus":"STOPPED","violationStatus":"NOT_VIOLATED","warnThreshold":32400000,"failedThreshold":64800000,"warnAt":"2022-10-31T10:12:57.086+0000","failAt":"2022-11-01T10:12:57.086+0000","startedAt":"2022-10-28T10:12:57.086+0000","pausedAt":null,"stoppedAt":"2022-10-28T10:14:07.975+0000","pausedDuration":0,"toFailTimeWorkDuration":null,"spent":70889,"previousSLAs":[],"startShiftedByPause":"2022-10-28T10:12:57.085+0000"}],"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-6","id":"6357d1b5007492273b161276","key":"ORG-6","version":5,"summary":"Ошибка в радаре","statusStartTime":"2022-10-28T08:44:23.927+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/2","id":"2","display":"Radar"}],"updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-10-28T08:44:23.933+0000","resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"start":"2022-10-25","description":"Не отслеживается грузовая партия 3162","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"createdAt":"2022-10-25T12:08:21.057+0000","tipZadac":["Техподдержка по продуктам"],"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"updatedAt":"2022-10-28T08:44:23.921+0000","status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false},{"self":"https://api.tracker.yandex.net/v2/issues/ORG-4","id":"6356801f007492273b15ff85","key":"ORG-4","version":5,"statusStartTime":"2022-10-24T12:11:33.910+0000","components":[{"self":"https://api.tracker.yandex.net/v2/components/1","id":"1","display":"Processor"}],"resolvedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"description":"Зарегистрировать пользователей в процессоре для РДМ","linia":"1 - линия","type":{"self":"https://api.tracker.yandex.net/v2/issuetypes/2","id":"2","key":"task","display":"Задача"},"resolution":{"self":"https://api.tracker.yandex.net/v2/resolutions/1","id":"1","key":"fixed","display":"Решен"},"previousStatusLastAssignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"createdAt":"2022-10-24T12:07:59.301+0000","tipZadac":["Техподдержка по продуктам"],"commentWithExternalMessageCount":0,"kanalObrasenia":["JivoSite"],"updatedAt":"2022-10-26T08:20:31.218+0000","summary":"Регистрация пользователя","updatedBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"resolvedAt":"2022-10-24T12:11:33.912+0000","start":"2022-10-24","priority":{"self":"https://api.tracker.yandex.net/v2/priorities/3","id":"3","key":"normal","display":"Средний"},"createdBy":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"commentWithoutExternalMessageCount":0,"votes":0,"assignee":{"self":"https://api.tracker.yandex.net/v2/users/337040592","id":"337040592","display":"SAM rus"},"queue":{"self":"https://api.tracker.yandex.net/v2/queues/ORG","id":"1","key":"ORG","display":"ЦЗС"},"status":{"self":"https://api.tracker.yandex.net/v2/statuses/8","id":"8","key":"closed","display":"Закрыт"},"previousStatus":{"self":"https://api.tracker.yandex.net/v2/statuses/1","id":"1","key":"open","display":"Открыт"},"favorite":false}]

**Comment by SAMmsk2** [comment]
I identified the issue but I don't know  how to resolve it. I can't construct a right if-statement! 
if I use Item("resolvedBy")<>empty then it works for the first line but doesn't work for the second becuase this key contains other keys.
if I use Item("resolvedBy")("display")<>empty it works for the second line but not for the first because there is no key "resolvedBy" in the first line.

**Comment by Deedolith** [comment]
Empty only apply to variant non object data types.
Yet, your item hold a dictionary.
Try with the IsEmpty() function.

**Comment by Nick-vanGemeren** [comment]
`ParseJson`will never give empty values in the structure.
I don't see a resolvedBy key group until item 4.
You will have a similar problem with the resolution key group.
Test for keys in`Dictionaries`using `Item.Exists(key)`
So, IF resolvedBy is always present with resolution, you can do something like:
```
    Dim keygroup As Dictionary
    If Item.Exists("resolution") Then
        Set keygroup = Item("resolvedBy")
        Sheets(1).Cells(i, 6) = keygroup("display")
        Set keygroup = Item("resolution")
        Sheets(1).Cells(i, 12) = keygroup("display")
    Else
        Sheets(1).Cells(i, 6) = ""
        Sheets(1).Cells(i, 12) = ""
      End If
```
If this solves your problem, please close your issue here.

**Comment by SAMmsk2** [comment]
> IsEmpty()

It helped.

**Comment by SAMmsk2** [comment]
Final solution that worked:

  If IsEmpty(Item("kanalObrasenia")) = False Then Sheets(1).Cells(i, 2).Value = Item("kanalObrasenia")(1)
        If IsEmpty(Item("kontaktnoeLico")) = False Then Sheets(1).Cells(i, 3).Value = Item("kontaktnoeLico")
        If IsEmpty(Item("klient")) = False Then Sheets(1).Cells(i, 4).Value = Item("klient")
        If IsEmpty(Item("telefon")) = False Then Sheets(1).Cells(i, 5).Value = Item("telefon")
        If IsEmpty(Item("email")) = False Then Sheets(1).Cells(i, 6).Value = Item("email")
        If IsEmpty(Item("createdBy")) = False Then Sheets(1).Cells(i, 7).Value = Item("createdBy")("display")
        If IsEmpty(Item("components")) = False Then Sheets(1).Cells(i, 8).Value = Item("components")(1)("display")
        If IsEmpty(Item("tipZadac")) = False Then Sheets(1).Cells(i, 9).Value = Item("tipZadac")(1)
