### ISSUE TITLE
object to json 

### ISSUE THREAD

**Issue by qtbhappy** [VBA-tools/VBA-JSON#25]
Hi, suppose in my excel, I have the following data
 name	profit
"p1"	        10
"p2"	         6
I want to convert them into json string like: "product":[{"name":"p1", "profit":10},{"name":"p2", "profit":6}]
I tried ConvertToJson, but failed.
Could you help me?

**Comment by timhall** [comment]
`ConvertToJson` takes in a `Dictionary` for objects and `Collection`/`Array` for arrays. In you case the shape to send to `ConvertToJson` would be the following:

```
Dictionary {
  product: Collection/Array [
    Dictionary {name: p1, profit: 10},
    Dictionary {name: p2, profit: 6}
  ]
}
```

```vb
Dim Products As New Collection
Dim Product As Dictionary
Dim Row As Long

For Row = 1 To 2
    Set Product = New Dictionary
    Product("name") = Cells(Row, 1).Value
    Product("profit") = Cells(Row, 2).Value
    Products.Add Product
Next Row

Dim Obj As New Dictionary
Set Obj("product") = Products

Dim Json As String
Json = ConvertToJson(Obj)
' => {"product":[{"name":"p1","profit":10},{"name":"p2","profit":6}]}
```

**Comment by qtbhappy** [comment]
great，thank  you so much

**Comment by qtbhappy** [comment]
By the way, when the profit is 0.6 in excel 2010, it is parsed to .6 in json string. How to parse it to 0.6.

In excel 2013, 0.6 in excel can be parsed to 0.6 in json correctly.

**Comment by qtbhappy** [comment]
I solved it.
I changed ConvertToJson = VBA.Replace(json_DictionaryCollectionOrArray, ",", ".") to  ConvertToJson = IIf(json_DictionaryCollectionOrArray > 0 And json_DictionaryCollectionOrArray < 1, "0" & VBA.Replace(json_DictionaryCollectionOrArray, ",", "."), VBA.Replace(json_DictionaryCollectionOrArray, ",", "."))
