### ISSUE TITLE
Too Many Line Continuations Error upon Import

### ISSUE THREAD

**Issue by vhn0912** [VBA-tools/VBA-JSON#258]
Unable to import the JsonConverter.bas into MS Excel Visual Basic 2021. I keep getting an error stating:
"Too many line continuations"

**Comment by alain-khalil** [comment]
I just tested on Excel2023 and it works fine. Can you please take a screenshot of the error ? Does it mention any line code ? 

The "Too many line continuations" error in VBA (Visual Basic for Applications) typically occurs when you have too many line continuation characters (underscore _) in a single line of code. VBA imposes a limit on the number of line continuation characters that can be used on a single line to improve code readability.

**Comment by vhn0912** [comment]
Thanks for your prompt response. No, it doesn't reference any line code but I re-downloaded the file and now it works! Thanks again.
