### ISSUE TITLE
ISO 8601 Conversion Failing 

### ISSUE THREAD

**Issue by arinazari** [VBA-tools/VBA-JSON#26]
Hi, 

"should convert dates to ISO 8601" returns:

>     X  Expected ["2003-01-03T00:05:06.000Z"] to match ["2003-01-02T

I ran the specs in  [VBA-tools/VBA-UTC](https://github.com/VBA-tools/VBA-UTC), and used "-420" for the UTC offset (PDT = -7). All tests passed. Not sure why the conversion would be off by a full day in VBA-JSON.

**Comment by timhall** [comment]
@arinazari Thanks for raising this issue, the tests may be a little too brittle here (especially if they're pass in VBA-UTC), I'll investigate.
