### ISSUE TITLE
JSON-VBA works on Windows 10/Access 2016 32bit but not Windows 11/Access 2021 64bit 

### ISSUE THREAD

**Issue by HankMcSpank** [VBA-tools/VBA-JSON#264]
I was previously using VBA-JSON successfully on Windows 10 (32 bit) ...I'm now using the exact same VBA code on Windows 11, but VBA-JSON is throwing up an error....

_______________________________
Run time error '458'

Variable uses an Automation tpe not supported in Visual Basic
______________________________

I searched & found  https://github.com/VBA-tools/VBA-JSON/issues/86 (issue 86).... which was closed with "Fixed in v2.2.4"

...I'm now using VBA-JSON v2.3.1 (I'm on Windows 11 Pro 23H2) ...but the problem persists... could do with a little coop by someone who has a handle on VBA-JSON

**Comment by DecimalTurn** [comment]
Did you step through the code and looked at the value in the locals window like they did in the issue you referenced? This would help identifying the exact source of the problem.

**Comment by HankMcSpank** [comment]
Hi, 

Ok, so it looks like this might be a case of me being rubbish at coding. My code (using VBA-JSON) worked ok on Windows 10 32 bit (Access 2016), but same code barfed on Windows 11 64 Bit (office 2021)...therefore I made a (wrong) assumption it was the change in operating system & Office version.

I've revisited my code today & made a few changes (so unfortunately I can't be precise about what the actual remedy was, my feeling is my code was iterating past the the point where it should have, so for example instead of doing 10 loops/iterations ...it was doing 11...which threw up an error. I can't account for why this wasn't happening on my pre updage PC though - same code.).

So hands up...this one was down to me, nothing to see here. Could some kind soul close the issue down?

Thank you.

**Comment by Nick-vanGemeren** [comment]
AFAIK only @timhall has maintenance rights. Although he is still active on Github, he hasn't done much here for years.
But you can close issues that you have opened.
There should be a 'close issue' option on your issue's page. (See [doc](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue))

**Comment by HankMcSpank** [comment]
(thanks ...just closed it myself :-) )
