### ISSUE TITLE
Non-standard null-value handling JsonConverter.ConvertToJson()

### ISSUE THREAD

**Issue by Merlin2001** [VBA-tools/VBA-JSON#27]
Hi!

### Issue
At the moment, null-values (Nothing in VBA) are outputted as (line breaks added for readability):
```javascript
{
   "Name": "MyObject",
   "Value": 42,
   "ChildObject": 
}
```
(where `ChildObject` Is `Nothing` in this specific instance)

This is (as far as I can see) not standard-conform and for example trips up the popular .NET package `Newtonsoft.Json`, when reading such a JSON file.

### Suggestion
Output Nothing-references as "null" which is allowed in the spec, like so:
```javascript
{
   "Name": "MyObject",
   "Value": 42,
   "ChildObject": null
}
```

To achieve this behavior, the following lines of code must be added between line **309** and **310** in *JsonConverter.bas*:

```vba
' Nothing
ElseIf VBA.TypeName(json_DictionaryCollectionOrArray) = "Nothing" Then
    json_BufferAppend json_buffer, "null", json_BufferPosition, json_BufferLength

```

**Comment by timhall** [comment]
Hi @Merlin2001 I've reproduced this issue. I'll fix it shortly.

**Comment by timhall** [comment]
Closed by https://github.com/VBA-tools/VBA-JSON/commit/5d2ad8b4a8fff547adcc3d7576e78f8bfc30db75
