### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by metawops** [VBA-tools/VBA-JSON#28]
Very helpful work, Tim! Much appreciated! :+1: 
However, I'm having issues with character encoding here. In the JSON answers I get from an internal (Intranet) service the strings are HTML-encoded (```&ouml;``` for an ö, ```&#252;``` for an ü, ```&#8211;``` for a longer hyphen: – etc.).
This is most certainly a problem on the service side and I **wish** I could give some character encoding request parameter to get an UTF-8 encoded answer, for example.
Unfortunately, this doesn't seem to be possible with this specific service call. :frowning: 
So I thought it would be helpful if VBA-JSON could do the magic if some configuration variable is set accordingly.
Is this something you would consider, Tim, or is this totally out of the question?

**Comment by timhall** [comment]
Hi @metawops, glad you're enjoying the library. This doesn't seem common enough to include in the library. It looks like the html entities will be passed through the parsing, so you should be able to decode them after parsing.

```vb
Sub Test
  Dim Parsed As Dictionary
  Set Parsed = JsonConverter.ParseJson("{""a"":""&pi;""}")

  Debug.Print ParseHtmlEntity(Parsed("a")) ' pi...
End Sub

Function ParseHtmlEntity(Encoded As String) As String
  ' Look for &...; and decode, I don't have any experience doing this :/
End Function
```

This functionality may be feasible by adding a "Visitor"-style interface that would allow custom functionality to be added during parsing/converting, but that's still in the rough planning stages at the moment.
