### ISSUE TITLE
Runtime error trying your example

### ISSUE THREAD

**Issue by Qinic** [VBA-tools/VBA-JSON#29]
Hi tried your example but getting Object required error on
ReDim Values(Parsed("values").Count, 3)

When I look at Parsed in watch window I can see it exists as a dictionary (with only 6 elements, expected thousands) 

Is it the code? Am I missing references? 
Attached the file I try to load into VBA (excel 2010) maybe you can shed some light

Thanks

[Planets.txt](https://github.com/VBA-tools/VBA-JSON/files/282402/Planets.txt)

**Comment by timhall** [comment]
Hi @Qinic, the example assumes the following format for the example json

```json
{
  "values": [
    {"a": 1, "b": 2, "c": 3},
    {"a": 4, "b": 5, "c": 6},
    {"a": 7, "b": 8, "c": 9},
  ]
}
```

In your Planets.txt, there is no root `values` item, so the `.Count` call is failing. You could iterate through something like the following, `Parsed("rst")("players").Count`, or something similar.

**Comment by Qinic** [comment]
Hi Tim,
ah I misunderstood the way this was parsing.
That makes sense, so I can either grabe certain array subs structures or
adapt the code to figure the structure out itself.
Anayway will play with this based on your input a bit and see how I best
ustelize it.
Thank you very much indeed.
Cheers
Qinic
