### ISSUE TITLE
Invalid Procedure Call or argument

### ISSUE THREAD

**Issue by ChevelleNV** [VBA-tools/VBA-JSON#31]
I am trying to parse a simple JSON object in Access VBA. I was able to output the json string using 'Debug.Print JsonConverter.ConvertToJson(JSON)'

which outputs 

`[{"Status":"ERROR","Message":"COULD NOT LOCATE ORIGINAL TRANSACTION\r"}]`

but when I try to access the element using

'JSON("Message")' 

I get a "Invalid procedure call or argument" any idea why?

![capture](https://cloud.githubusercontent.com/assets/828558/16506584/5459240c-3ed8-11e6-9948-adbbf6b12d6f.JPG)

**Comment by timhall** [comment]
Looks like it's inside an array, I think this will work: `JSON(1)("Message")` (note: arrays are converted to `Collection`, which are 1-based)

**Comment by ChevelleNV** [comment]
That seemed to do the trick...
