### ISSUE TITLE
The function fails to execute

### ISSUE THREAD

**Issue by AlekseyGor** [VBA-tools/VBA-JSON#33]
Here is a JSON file, returned by a web-service

{"status":true,"data":{"minute":{"eth":64.73209428000526,"dollars":0.03445805896294384,"bitcoins":0.00006084816862320494},"hour":{"eth":3883.925656800315,"dollars":2.0674835377766305,"bitcoins":0.0036508901173922964},"day":{"eth":93214.21576320757,"dollars":49.61960490663913,"bitcoins":0.08762136281741512},"week":{"eth":652499.510342453,"dollars":347.33723434647396,"bitcoins":0.6133495397219059},"month":{"eth":2796426.472896227,"dollars":1488.588147199174,"bitcoins":2.6286408845224534}}}

The function "JsonConverter. ParseJson" cannot parse this JSON. It crashes somewhere inside. It's a correct JSON. Why does it crash?

**Comment by daneelolivawr** [comment]
Hi,
writing your JSON in a txt file and parsing it with the following code I encounter no errors...

As usual, after the "STOP" command, you can look to the variable "Parsed" in the "Locals Window" to see the parsed content.

```
Dim FSO As New FileSystemObject
Dim JsonTS As TextStream
Dim JsonText As String
Dim Parsed As Dictionary

' Read .json file
Set JsonTS = FSO.OpenTextFile("C:\e3-shared\@gitwk\PiccolaImpresaShared2.gitwk\client excel\temp.txt", ForReading)
JsonText = JsonTS.ReadAll
JsonTS.Close

' Parse json to Dictionary
' "values" is parsed as Collection
' each item in "values" is parsed as Dictionary
Set Parsed = JsonConverter.ParseJson(JsonText)

Stop
```

**Comment by stefano77it** [comment]
Hi,
writing your JSON in a txt file and parsing it with the following code I encounter no errors...

As usual, after the "STOP" command, you can look to the variable "Parsed" in the "Locals Window" to see the parsed content.

```
Dim FSO As New FileSystemObject
Dim JsonTS As TextStream
Dim JsonText As String
Dim Parsed As Dictionary

' Read .json file
Set JsonTS = FSO.OpenTextFile("C:\e3-shared\@gitwk\PiccolaImpresaShared2.gitwk\client excel\temp.txt", ForReading)
JsonText = JsonTS.ReadAll
JsonTS.Close

' Parse json to Dictionary
' "values" is parsed as Collection
' each item in "values" is parsed as Dictionary
Set Parsed = JsonConverter.ParseJson(JsonText)

Stop


```

**Comment by timhall** [comment]
Hi @AlekseyGor I'm sorry you're having an issue with the library, but I was able to successfully parse this json with no errors. I'll be happy to look at it further if you can include a more complete test case.
