### ISSUE TITLE
multiple levels of keys

### ISSUE THREAD

**Issue by wlmfa** [VBA-tools/VBA-JSON#35]
Hey!

How can I access multiple levels of keys? 
For exemple, here's a shortened json
"{""level1"":{""item1"":""A"",""item2"":""B"",""item3"":[{""item3.1.1"":""AA"",""item3.1.2"":""AB"",""item3.1.3"":""AC"",""item3.1.4"":""AD"",""item3.1.5"":""AE",""item3.1.6"":{""item3.1.6.1"":2,""item3.1.6.2"":3,""item3.1.6.3"":2,""item3.1.6.4"":1,""item3.1.6.5"":1},""item3.1.7"":{""item3.1.7.1"":49,""item3.1.7.2"":151,""item3.1.7.3"":49,""item3.1.7.4"":1162},""item3.1.8"":{""item3.1.8.1"":2,""item3.1.8.2"":-1,""item3.1.8.3"":0,""item3.1.8.4"":0}},{""item3.2.1"":""BA"",""item3.2.2"":""BB"",""item3.2.3"":""BC"",""item3.2.4"":""BD"",""item3.2.5"":""BE"",""item3.2.6"":{""item3.2.6.1"":8,""item3.2.6.2"":6,""item3.2.6.3"":8,""item3.2.6.4"":2,""item3.2.6.5"":5},""item3.2.7"":{""item3.2.7.1"":36,""item3.2.7.2"":135,""item3.2.7.3"":36,""item3.2.7.4"":1124},""item3.2.8"":{""item3.2.8.1"":1,""item3.2.8.2"":-6,""item3.2.8.3"":0,""item3.2.8."":0}}}],""item4"":1,""item5"":true}
}"

How can i get item 3.1.6.1 value?

I've tried
Set json = JsonConverter.ParseJson(json)
Debug.Print json("level1")(1) 'does not work

I also tried, as the example
For Each Value In json("level1")
  Values(i, 0) = Value("item1") 'it works
  Values(i, 1) = Value("item2") 'it works
  Values(i, 2) = Value("item3") 'does not work 
  Values(i, 2) = Value("item3")(1) 'does not work 
  Values(i, 2) = Value("item3")("item3.1.1") 'does not work
  i = i + 1
Next Value

Thank you!

**Comment by wlmfa** [comment]
I changed "Values" and "Value" for sth else and it worked. I dont know why.

valor(i, 2) = valores("item3")("item3.1.1") 'this worked

I'm sorry.

**Comment by timhall** [comment]
No worries, I'm glad it worked!
