### ISSUE TITLE
Function fails to execute (improper use of the keyword new)

### ISSUE THREAD

**Issue by Xyolyp** [VBA-tools/VBA-JSON#36]
First of all, thank you for this beaty even though I couldn't get it to work in any way.

Latest Version 
`Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary`
throws the error from the title on the third line with code.(`    Set json_ParseObject = New Dictionary`)
I hope you can help me

**Comment by introcoder** [comment]
Just put Scripting.Dictionary and ot should work. Cheers.

**Comment by Xyolyp** [comment]
Now sadly the error is a few lines below :/ 
I changed the line `Set json_ParseObject = New Dictionary` to `Set json_ParseObject = New Scripting.Dictionary` and the error is "Method or data object not found" in `Set json_ParseObject.Item(json_Key) = json_ParseValue(json_String, json_Index)` and it highlights the "`.Item(json_Key) =`" part of it.

**Comment by Xyolyp** [comment]
The version 2.2.0 seems to work by now :+1:
