### ISSUE TITLE
vba dictionary

### ISSUE THREAD

**Issue by matdestr** [VBA-tools/VBA-JSON#38]
How to add the VBA dictionary on mac?

**Comment by timhall** [comment]
Hi @matdestr, download the [latest release](https://github.com/VBA-tools/VBA-Dictionary/releases) of VBA-Dictionary, unzip, and add `Dictionary.cls` to your project.

**Comment by timhall** [comment]
Thanks for raising this issue, I've added an installing section to VBA-Dictionary: https://github.com/VBA-tools/VBA-Dictionary#installing
