### ISSUE TITLE
How to import the file on mac?

### ISSUE THREAD

**Issue by matdestr** [VBA-tools/VBA-JSON#39]

**Comment by timhall** [comment]
Hi @matdestr I haven't tried the newest update for Mac, but it looks like it may not be supported (which has to be a bug, I can't believe they would intentionally take it out). I'll look into this and get back to you.

http://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_mac/importing-macro-modules-into-excel-visual-basic/905b01cf-78ce-4bfc-9f93-9f7dda137101

**Comment by matdestr** [comment]
Thanks!

Kind regards,
Mathisse De Strooper

-- 
*Mathisse De Strooper*





( m ) +32 474054598 <//+YOURNUMBERNOSPACES>
( e ) mathisse.de.strooper@gmail.com <mathisse.destrooper@collibra.com>
( t ) @matdestr <http://www.twitter.com/@matdestr>
( ln ) linkedin.com/in/mathissedestrooper
<https://www.linkedin.com/in/mathissedestrooper>

On September 19, 2016 at 6:21:44 PM, Tim Hall (notifications@github.com)
wrote:

Hi @matdestr <https://github.com/matdestr> I haven't tried the newest
update for Mac, but it looks like it may not be supported (which has to be
a bug, I can't believe they would intentionally take it out). I'll look
into this and get back to you.

http://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_mac/importing-macro-modules-into-excel-visual-basic/905b01cf-78ce-4bfc-9f93-9f7dda137101

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/VBA-tools/VBA-JSON/issues/39#issuecomment-248041642>,
or mute the thread

**Comment by matdestr** [comment]
Even if I am just copying the files, I'm getting errors all over the place...

**Comment by zcrowe** [comment]
Did anyone manage to find a solution to this?  I also can't see/find a way to import this unfortunately!

**Comment by tamlyn10** [comment]
Likewise

**Comment by MilapNaik** [comment]
Any solution?

**Comment by timhall** [comment]
The importing of this should be fixed in the latest Mac, do have another bug, but fixing that in #86

**Comment by carlsenk** [comment]
Not fixed yet.  But I found a workaround by opening the specs spreadsheet.  It contains a copy of the imported code, then copied the module into my spreadsheet.
