### ISSUE TITLE
How to access this value in json?

### ISSUE THREAD

**Issue by lucnap** [VBA-tools/VBA-JSON#40]
{"messages":[{"to":"3912345678912","status":{"groupId":1,"groupName":"PENDING","id":7,"name":"PENDING_ENROUTE","description":"Message sent to next instance"},"smsCount":1,"messageId":"3b3133a6-ea68-48cb-ac64-342fb8566e58"}]}

I tried to access value groupName as json("messages")(0)("status")("groupName") but is invalid

**Comment by lucnap** [comment]
ok found the answer, to access that key, use the following syntax
json("messages")(1)("status")("groupName")
Array's first element is 1 and not 0

**Comment by timhall** [comment]
Hi @lucnap, beat me to it. VBA-JSON uses `Collection` for arrays, which are 1-based (an annoying thing to remember).
