### ISSUE TITLE
Update new line handling

### ISSUE THREAD

**Issue by Teatabler** [VBA-tools/VBA-JSON#41]
In line 560, in my opinion, Chr(10) is better than vbCrLf.

```
559      Case "n"
560           json_BufferAppend json_buffer, vbCrLf, json_BufferPosition, json_BufferLength
561           json_Index = json_Index + 1
```

**Comment by timhall** [comment]
Related: https://github.com/VBA-tools/VBA-Web/issues/270

**Comment by omegastripes** [comment]
I converted the sample `{"text":"abc\r\ndef"}` to object with ParseJson, then converted it to string with ConvertToJson, returned string is```
{
	"text": "abc\r\r\ndef"
}```
Seems ConvertToJson duplicates `\r` within strings.

**Comment by timhall** [comment]
A little more activity on #67 closing in favor of that.
