### ISSUE TITLE
How to print off the data within field 'b'

### ISSUE THREAD

**Issue by TESAARON** [VBA-tools/VBA-JSON#43]
Hello!

I am having an issue printing the values under attribute "b" in one single column from your example JSON:

' -> "{
'       "a": 123,
'       "b": [
'         1,
'         2,
'         3,
'         4
'       ],
'       "c": {
'         "d": 456,
'         "e": 789  
'       }
'     }"

So that I could get a result like the following:

a        b    cd      ce
123    1    456    789
123    2    456    789
123    3    456    789
123    4    456    789

I am trying the following approach but still having issues:

i = 2

For Each Item In JSON
    ws.Cells(i, 1).Value = Item("a")
    ws.Cells(i, 2).Value = Item("b")(i)
i = i + 1
Next

Any ideas what I could try?

Regards,
Aaron

**Comment by TESAARON** [comment]
Perhaps if there was a way to get the number of items within 'b' then I could perform a nested loop?

Do you know how I could get this number?

**Comment by timhall** [comment]
JSON arrays are converted to `Collection` so you can find the number of items with `Item("b").Count` and I think a nested loop should work fine for your case, just remember that Collection's are 1-based (as opposed to arrays being 0-based by default)

**Comment by TESAARON** [comment]
Hi timhall,

Many thanks, that works perfectly!

Aaron
