### ISSUE TITLE
Not Able to run Code in Word

### ISSUE THREAD

**Issue by parthrawal** [VBA-tools/VBA-JSON#46]
I have been trying to use this .bas file to apply in my current project (Word Document). however when i run the code. It keeps throwing an error "Wrong Number of arguments"  even though i have given the "Microsoft Scripting Runtime" reference in my project.

Any Ideas?

**Comment by timhall** [comment]
This issue sounds familar, but I can't remember what caused it. I'll look into it.

**Comment by parthrawal** [comment]
Hi,
Sorry I did Solve the Issue by Telling what to refer to , "Scripting.Dictionary" solved the Issue for me. But interestingly I have written Same sort of code on MS Project and on Word Document. Error did not occur on the MS Project but Word threw an error. Don't know why. As both the applications are on the same machine.

**Comment by rrouquier** [comment]
Hi all, partharawal,

I am facing the same error. When I test the code with the example provided, it work perfectly fine :

`Set JSON = JsonConverter.ParseJson("{""a"":123,""b"":[1,2,3,4],""c"":{""d"":456}}")
MsgBox JSON("responseStatus")`

![image](https://user-images.githubusercontent.com/29275681/26924314-ed9630a8-4c77-11e7-8a59-30fca3deaf4f.png)


However, when I plug it to an online API, I have the "Wrong Number of arguments" error message.
Here is my code :

`Sub GetJSON()

    Set MyRequest = CreateObject("WinHttp.WinHttpRequest.5.1")
    MyRequest.Open "GET", "https://api.kraken.com/0/public/Time"
    MyRequest.Send

    Dim JSON As Object
    Set JSON = JsonConverter.ParseJson(MyRequest.ResponseText)
    MsgBox JSON("result")
    
End Sub`

![image](https://user-images.githubusercontent.com/29275681/26924695-77e7af56-4c79-11e7-8c79-979c48535f1a.png)

Any idea on what do I get this error ?

**Comment by parthrawal** [comment]
Public Function CallREST(Method As String, RequestData As String) As String
    Dim MyRequest As Object
    Set MyRequest = CreateObject("WinHttp.WinHttpRequest.5.1")
    MyRequest.Open "POST", _
    "https://aaa.bbb.com/api/RMO/" & Method & ""
    MyRequest.SetRequestHeader "Content-type", "application/json"
    'Send Request.
    MyRequest.Send (RequestData)
    CallREST = MyRequest.ResponseText
End Function

Above function works for me. Let me know if you need more details.
![reference](https://user-images.githubusercontent.com/12444341/26970298-7eafe3aa-4d26-11e7-9ff6-795b16e6584f.PNG)

**Comment by timhall** [comment]
Not positive, but this seems related to https://github.com/VBA-tools/VBA-JSON/issues/68
