### ISSUE TITLE
User-defined type not defined 

### ISSUE THREAD

**Issue by DennisChrDk** [VBA-tools/VBA-JSON#47]
Do you know what could be the problem here? I've imported the code into my excel document, But every time I try to run my macro I get the following error on the following line of code from the JsonConverter:

Compile Error: User-defined type not defined 

Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary

EDIT: I didn't see the resolved problems, but I get it to work after adding the reference to Microsoft Scripting Runtime. Thanks for sharing this!

**Comment by ghothan** [comment]
Denis,

How did you resolve this issue?

**Comment by DennisChrDk** [comment]
> Denis,
> 
> How did you resolve this issue?

As far as I remember, you need need to add Microsoft Scripting Runtime as a reference in VBA:
- Alt + F11
- "Tools" 
- "Reference"
- Find "Microsoft Scripting Runtime" and add it
