### ISSUE TITLE
[Question] Documentation style and parsing

### ISSUE THREAD

**Issue by mattpalermo** [VBA-tools/VBA-JSON#48]
I've noticed that you have used a JavaDoc / Doxygen like style to markup your code documentation. I am curious if you use any tools that can parse this documentation, or do you use it for the sake of using a common style?

I ask because I am exploring this topic for my self at the moment, specifically for VBA code, and found your code to be an interesting example.

Here is a reddit thread where I am exploring the same topic: https://www.reddit.com/r/vba/comments/5trrym/vba_comment_documentation_styles_and_tools/

**Comment by timhall** [comment]
Thanks for the question. I picked the style up from jsdoc, but it's all pretty much the same style. No tools for it just yet, but have big plans for the future, hoping to have it be part of https://www.vba-blocks.com/ which is nearing an initial release for build support.

**Comment by mattpalermo** [comment]
Thank you for your answer.

I look forward to seeing VBA Blocks up and running. It's interesting and I always keep an eye on it to see what you've been up to. Unfortunately I won't be able to test or enjoy it since I've moved away from using VBA for the time being.
