### ISSUE TITLE
Check if property exist

### ISSUE THREAD

**Issue by Martin-Hogge** [VBA-tools/VBA-JSON#56]
Is their any way to check if a property exist? When I try to access a property that is not in a JSON file it throws a 450 error.

**Comment by timhall** [comment]
Hi @Martin-Hogge you can use `Exists` for objects and check for array bounds with `Count`.

```vb
Dim Value As Dictionary
Set Value = JsonConverter.ParseJson("{""a"":[1,2,3],""b"":{""c"":""d""}}")

If Value.Exists("a") Then
  For i = 1 to Value("a").Count
    '     ^ (Collections are 1-based)
  Next i
End If

If Not Value.Exists("missing") Then
  ' Not found
End If
```

Additionally, you can check what keys an object (`Dictionary`) contains with `Keys`.

```vb
Dim Value As Dictionary
Set Value = JsonConverter.ParseJson("{""a"":1,""b"":2,""c"":3})

Dim Key As Variant
'          ^ Variant is needed for For Each with strings

For Each Key In Value.Keys
  Debug.Print Key
Next Key
' -> a, b, c
```

**Comment by prasannarathi** [comment]
How to handle a situation when you have a nested structure in JSON message and want to ensure "field A" always exists?  Exists function doesn't allow multiple fields to be added.

{ "Issues":[
 "Field 1": {
    "InnerField" : {
      "fieldA" : "test A"
      "fieldB": "test B"
      -- More fields here
     }
    "InnerField":{
      "fieldB": "test B"
      -- More fields here
    },
   },
  ],
}
