### ISSUE TITLE
Problem accessing JSON

### ISSUE THREAD

**Issue by PeterBundeHansen** [VBA-tools/VBA-JSON#58]
Please help me. I just want to read out attributes from the text string that I have attached in the attached file, from within Excel VBA.  I tried all kinds of code from the examples but it doesnt Work.

When I look at the file in XMLSpy it looks fine. Why does it not Work in Excel VBA, using the example code? Please propose sample code where I can retrieve the 'id' 's and then use each id to access the attributes.

I tried using a Dictionary type variable to store the .ParseJson result but Excel says it is a type mismatch.

[commentsJSON.zip](https://github.com/VBA-tools/VBA-JSON/files/1001496/commentsJSON.zip)

**Comment by gnumoreno** [comment]
Peter, 

Take a look at the code and json file I'm using here:

https://github.com/VBA-tools/VBA-JSON/issues/59

With very little adaptation I think you will be able to make it work for you. 

Let me know if you need any help.

Regards,

**Comment by timhall** [comment]
Looks like a top-level array issue, you can use the following:

```vb
Dim Comments As Collection
Set Comments = JsonConverter.ParseJson("...")

Dim Comment As Dictionary
For Each Comment in Comments
  Debug.Print Comment("authorDisplayName") & " said " & Comment("body")
Next Comment
```
