### ISSUE TITLE
Having problems with array in JSON

### ISSUE THREAD

**Issue by gnumoreno** [VBA-tools/VBA-JSON#59]
First, thank you for creating this! Even though I'm a beginner (to VBA-JSON and VBA in general - it is my first program!) I was able to make it work.

Nevertheless I can' t make it work for an array contained in the json, specifically the ip_address.

"ip_address": ["192.168.0.1", "192.168.0.38", "192.168.0.39", "192.168.0.40", "192.168.0.41", "192.168.0.42", "192.168.0.43", "192.168.0.161"],

I'm providing you with the Sub and an json example. I hope you can point me to a workaround or fix.

```
Sub ParseJson()

Dim FSO As New FileSystemObject
Dim JsonTS As TextStream
Dim JsonText As String
Dim Parsed As Dictionary

Set JsonTS = FSO.OpenTextFile("bla.json", ForReading)
JsonText = JsonTS.ReadAll
JsonTS.Close

Set Parsed = JsonConverter.ParseJson(JsonText)


Dim Rows As Variant
ReDim Rows(Parsed("rows").Count, 4)

Dim Row As Dictionary
Dim i As Long

i = 0
For Each Row In Parsed("rows")
  Rows(i, 0) = Row("id")
  Rows(i, 1) = Row("host_name")
  Rows(i, 2) = Row("dns_name")
  Rows(i, 3) = Row("os")
  Rows(i, 4) = Row("ip_address")

  i = i + 1
Next Row

Sheets("Sheet1").Range(Cells(1, 1), Cells(Parsed("rows").Count, 4)) = Rows

End Sub
```

```
{
	"total": 2,
	"rows": [{
			"id": 2,
			"parent_id": 175,
			"type": "virtual",
			"os": "AIX 7.1",
			"host_name": "blablabla",
			"dns_name": "blablabla.example.com",
			"ip_address": ["192.168.0.1", "192.168.0.38", "192.168.0.39", "192.168.0.40", "192.168.0.41", "192.168.0.42", "192.168.0.43", "192.168.0.161"],
			"last_seen": "2017-05-31T07:03:18Z",
			"hardware_manufacturer": "IBM",
			"hardware_model": "IBM,9117-MMC",
			"hardware_serial_number": "10462E2",
			"processor_brand_string": "PowerPC_POWER7",
			"processor_type": "Multi-core",
			"processor_brand": "POWER7(770,780,795 servers)",
			"processor_vendor": "IBM(R)",
			"processor_model": "All Existing",
			"partition_cores": "2.0",
			"server_processors": 16,
			"server_cores": 16
		}, {
			"id": 4,
			"parent_id": 182,
			"type": "virtual",
			"os": "AIX 7.1",
			"host_name": "blebleble",
			"dns_name": "blebleble.example.com",
			"ip_address": ["192.168.0.47"],
			"last_seen": "2017-05-31T06:56:41Z",
			"hardware_manufacturer": "IBM",
			"hardware_model": "IBM,9117-570",
			"hardware_serial_number": "100C0FA",
			"processor_brand_string": "PowerPC_POWER5",
			"processor_type": "Dual-core",
			"processor_brand": "Power5(TM)",
			"processor_vendor": "IBM(R)",
			"processor_model": "All Existing",
			"partition_cores": "1.0",
			"server_processors": 16,
			"server_cores": 16
		}
	]
}
```

**Comment by gnumoreno** [comment]
I noticed that there is the function json_ParseArray. I just don' t know how to use it. :-(

Can someone provide an example for the ip_address array?

**Comment by zgrose** [comment]
Example:

````
Public Sub ReadingFromAnArray()

    Dim jObject As Dictionary
    Dim el As Dictionary
    Dim i As Long
    
    Set jObject = ParseJson("{ ""total"":2, ""rows"":[ {""id"":2}, {""id"":4}] }")
    
    ' This example assumes you know what you're getting so takes lots of liberties
    
    Debug.Print "The object says there are " & jObject("total") & " rows."
    
    For Each el In jObject("rows")
        Debug.Print "row id is " & el("id")
    Next el
    
    ' alternate approach
    For i = 1 To jObject("total")
        Debug.Print "row #" & i & " is id of " & jObject("rows")(i)("id")
    Next i
    
End Sub
````

Output:

````
The object says there are 2 rows.
row id is 2
row id is 4
row #1 is id of 2
row #2 is id of 4
````

**Comment by ridders52** [comment]
Hi
I've only just seen this post.
If you still need a solution, I have analysed the file using an application called JSON Analyse and Transform for Access which is available via my website. [http:www.mendipdatasystems.co.uk](url)

The file has 19 fields including an added PK field and ip_address in its own subarray
The file structure is shown in the attached PDF
[rptJSONFileStructure.pdf](https://github.com/VBA-tools/VBA-JSON/files/1609442/rptJSONFileStructure.pdf)

The screenshot below shows part of the 2 normalised tables created in Access
![gnumereno tables](https://user-images.githubusercontent.com/34749836/34645994-84be160c-f354-11e7-9d5a-88bdda327274.PNG)

If you are interested, the **JSON Analyse and Transform for Access (JATFA)**  application has been designed to make importing and handling JSON files a straightforward and, in many cases, a largely automated task.

Features include:
a) Fully automated analysis of JSON files including handling of subarrays
b) Fully automated creation of tables and transform functions based on file analysis.
c) Import JSON data into normalised Access tables based on file analysis
d) Over 90 sample JSON files are supplied as examples

In the vast majority of cases, the file analysis will work with no user intervention required. However, users can choose to treat individual files as a special case, allowing the default analysis procedure you to be overwritten for that file.

For further details, see [](http://www.mendipdatasystems.co.uk/json-analyse-transform/4594138310).
