### ISSUE TITLE
Unquoted key value

### ISSUE THREAD

**Issue by pm63** [VBA-tools/VBA-JSON#60]
Hi,
the JSON I need to parse has unquoted null values like this:
"next_page":null,
I need to reiterate the request in VBA as many times as there are pages (the value gets populated with the URL pointing at the next page) then stop when the value is null, but as it's not within double quotation marks the "if then" statement I am using doesn't see null as a value.
I can see an AllowUnquotedKeys option but I'm not quite sure how to make it active.
Can someone help please?
Many thanks.
Pierugo

**Comment by zgrose** [comment]
There might be other ways and this issue is pretty odd but in case anyone asks again here is a snippet on how to work with null values.

````
Public Sub ValueIsNullExample()

    Dim jObject As Dictionary
    
    Set jObject = ParseJson("{ ""foo"":""bar"", ""baz"":null, ""boz"":[], ""abc"":{} }")
    
    Debug.Print "foo is null = " & (VarType(jObject("foo")) = vbNull)
    Debug.Print "baz is null = " & (VarType(jObject("baz")) = vbNull)
    Debug.Print "boz is null = " & (VarType(jObject("boz")) = vbNull)
    Debug.Print "abc is null = " & (VarType(jObject("abc")) = vbNull)
    Debug.Print ConvertToJson(jObject)
    
    Set jObject = New Dictionary
    
    jObject.Add "foo", "bar"
    jObject.Add "baz", Null
    jObject.Add "boz", New Collection
    jObject.Add "abc", New Dictionary
    
    Debug.Print "foo is null = " & (VarType(jObject("foo")) = vbNull)
    Debug.Print "baz is null = " & (VarType(jObject("baz")) = vbNull)
    Debug.Print "boz is null = " & (VarType(jObject("boz")) = vbNull)
    Debug.Print "abc is null = " & (VarType(jObject("abc")) = vbNull)
    Debug.Print ConvertToJson(jObject)

End Sub
````

You should see in the immediate window (I happened to be in Excel):

````
foo is null = False
baz is null = True
boz is null = False
abc is null = False
{"foo":"bar","baz":null,"boz":[],"abc":{}}
foo is null = False
baz is null = True
boz is null = False
abc is null = False
{"foo":"bar","baz":null,"boz":[],"abc":{}}
````

**Comment by timhall** [comment]
VBA-JSON has built-in null handling and @zgrose 's answer is great. I'll just add you can use `VBA.IsNull(...)` as shorthand for `VarType(...) = vbNull`
