### ISSUE TITLE
In a loop, provide the same result each time.

### ISSUE THREAD

**Issue by NicoIasOnGithub** [VBA-tools/VBA-JSON#63]
Hi everybody,

The JSON converter is great, thanks a lot.

I need to download the same JSON file online every 5 min (the JSON file is updated on real time). But, when I do so, the result from the JSON converter is always the same. I have to close the workbook, and re-open it to get a new version of the JSON file converted thanks to the JSON converter.

I have the following macro ReadJson() in a loop.

I haven't found out how solving this issue. Thanks a lot for your help.

NicolasIsOnGithub

Option Explicit 
Public Const AddressHttp = "https://www.xxx.com/jsonfile"
Public Frecuency As Double 
Public DurationInHours As Integer 
Public i As Integer

Private Sub ReadJson()

Dim JSON As Object
Dim JS As Variant, Item As Variant
Dim Moment As Date

Dim http As Object
Set http = CreateObject("MSXML2.XMLHTTP")

http.Open "GET", AddressHttp, False

http.Send

Set JSON = ParseJson(http.responseText)

Set JS = JSON("placemarks") 

Moment = Now

For Each Item In JSON("placemarks")
    Sheets(1).Cells(i, 1).Value = Item("1")
    Sheets(1).Cells(i, 2).Value = Item("2")  
    Sheets(1).Cells(i, 3).Value = Item("3")
    Sheets(1).Cells(i, 4).Value = Item("4")
    Sheets(1).Cells(i, 5).Value = Moment
      i = i + 1
Next

End Sub

**Comment by timhall** [comment]
My guess is that the response is being cached by `MSXML2.XMLHTTP`, a very frustrating issue. There are some workarounds, including appending a "cache breaker" querystring ([SO Question](https://stackoverflow.com/questions/3055475/vbscript-disable-caching-of-response-from-server-to-http-get-url-request)). An alternative would be to check out [VBA-Web](https://github.com/VBA-tools/VBA-Web), it'll handle a lot of this for you:

```vb
Private Sub ReadJson()
  Dim Json As Collection
  Dim Client As New WebClient
  Dim Response As New WebResponse
  Dim Moment As Date
  Dim i As Long

  Set Response = Client.GetJson(AddressHttp)
  Set Json = Response.Data
  Moment = Now

  For Each Item In Json("placemarks")
    Sheets(1).Cells(i, 1).Value = Item("1")
    Sheets(1).Cells(i, 2).Value = Item("2")
    Sheets(1).Cells(i, 3).Value = Item("3")
    Sheets(1).Cells(i, 4).Value = Item("4")
    Sheets(1).Cells(i, 5).Value = Moment
    i = i + 1
  Next
End Sub
```

**Comment by NicoIasOnGithub** [comment]
Thanks Tim for your help. I have download VBA-WEB blank file, and copied every modules in my Excel file. And now I have to handle a 80042b04 error (with http request). How can I solve it ? Thanks!
