### ISSUE TITLE
Changing Date Format

### ISSUE THREAD

**Issue by troygraham** [VBA-tools/VBA-JSON#65]
How can i change the date format so it doesn't look like this:

2017-08-01T00:11:32.0000000+00:00

and actually looks like this:

01/08/2017 11:32am

Do i need to change the JSONConverter.bas module coding ?? If so what do i change ?

**Comment by timhall** [comment]
Hi @troygraham you can change [Line 246](https://github.com/VBA-tools/VBA-JSON/blob/43f197e1907c79b4b3db7dd166a79d633669ce4c/JsonConverter.bas#L246) for your format or you can simply convert the dates to strings before passing them to `JsonConverter`. I would recommend the second approach if you can, here's an example for a data `Dictionary`.

```vb
Function ToJson(Data As Dictionary) As String
  Dim Intermediate As New Dictionary
  Dim Key As Variant
  For Each Key In Data.Keys
    If Key = "date_value" Then
      Intermediate.Add Key, ToDate(Data{Key))
    Else
      Intermediate.Add Key, Data{Key)
    End If
  Next Key

  ToJson = JsonConverter.ConvertToJson(Intermediate)
End Function

Function ToDate(Value As Date) As String
  ' -> To your format
End Function
```

**Comment by troygraham** [comment]
Hi Tim,

Thanks for your reply.

I am still new to VBA Coding, so I am unsure exactly what to put in the Function coding to get it to work.

Can you shed some light on this.


Regards

Troy Graham | IT Support Administrator | ECL Group Australia Pty Ltd | +61 429 893 373

**Comment by fjf2002** [comment]
Maybe your problem is, how to parse the json date string back to a VBA Date data type.

Simply call `ParseIso("2017-08-01T00:11:32.0000000+00:00")`
