### ISSUE TITLE
Unable to parse JSON String

### ISSUE THREAD

**Issue by ryanclouse** [VBA-tools/VBA-JSON#70]
Howdee, the following string is not able to be parsed. I cannot access the "addresses" object in this JSON. I was able to do so through Newtonsoft.JSON in C#.

{
    "latitude": 52.24593734741211,
    "longitude": -0.891636312007904,
    "addresses":
    ["10 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "12 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "14 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "16 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "18 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "2 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "20 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "22 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "24 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "26 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "26a Watkin Terrace, , , , , Northampton, Northamptonshire",
    "26b Watkin Terrace, , , , , Northampton, Northamptonshire",
    "26c Watkin Terrace, , , , , Northampton, Northamptonshire",
    "26d Watkin Terrace, , , , , Northampton, Northamptonshire",
    "28 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "2a Watkin Terrace, , , , , Northampton, Northamptonshire",
    "30 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "32 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "36 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "38 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "4 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "40 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "40b Watkin Terrace, , , , , Northampton, Northamptonshire",
    "42 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "44 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "46 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "48 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "50 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "8 Watkin Terrace, , , , , Northampton, Northamptonshire",
    "Flat 1, 6 Watkin Terrace, , , , Northampton, Northamptonshire",
    "Flat 1, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 2, 6 Watkin Terrace, , , , Northampton, Northamptonshire",
    "Flat 2, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 3, 6 Watkin Terrace, , , , Northampton, Northamptonshire",
    "Flat 3, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 4, 6 Watkin Terrace, , , , Northampton, Northamptonshire",
    "Flat 4, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 5, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 6, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 7, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 8, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire",
    "Flat 9, Watkin Court, Watkin Terrace, , , Northampton, Northamptonshire"]
}

**Comment by dymeng** [comment]
Likewise with the following.  It's oddly formatted, but valid (I forget which service this came from, but was "live data" from a service I had to work with).  I ended up using the Microsoft JScript engine to do the parsing (here: https://dymeng.com/parsing-json-with-vba/) and there's a more drawn out discussion of parsers here: http://www.utteraccess.com/forum/index.php?showtopic=2045170&hl=

`[
  {
    "customer": {
      "first_name": "blah",
      "last_name": "blah"
    }
  },
  {
    "customer": {
      "first_name": "blah",
      "last_name": "blah"
    }
  },
  {
    "customer": {
      "first_name": "blah",
      "last_name": "blah"
    }
  }
]`

**Comment by Vaggeto** [comment]
Jac/Dymeng, I had an issue regarding your solution but sadly the page you linked to doesn't appear to allow comments, so I'll include it here instead:
Hi, any ideas on how to get this working in Excel 2010?

There are a few incompatibilities that I modified the code to workaround:
-'Option Compare Database is not available. Binary or Text are the only Option Compare choices.
- FileSys.FileToString doesn't seem to be compatible so I used another method to read the .json file into a string.

After that though I run into "error 429: ActiveX component can't create object." here:
Public Sub InitScriptEngine()
    Set ScriptEngine = CreateObject("MSScriptControl.ScriptControl") 'New ScriptControl

I confirmed I do have MicrosoftScript control active 1.0 enabled.

Any ideas?

**Comment by ridders52** [comment]
I have created an application called **JSON Analyse and Transform for Access (JATFA)** which is available via my website. This application has been designed to make importing and handling JSON files a straightforward and, in many cases, a largely automated task.

Features include:
a) Fully automated analysis of JSON files including handling of subarrays
b) Fully automated creation of tables and transform functions based on file analysis.
c) Import JSON data into normalised Access tables based on file analysis
d) Over 90 sample JSON files are supplied as examples

In the vast majority of cases, the file analysis will work with no user intervention required. However, users can choose to treat individual files as a special case, allowing the default analysis procedure you to be overwritten for that file.

For info, both JSON files listed above are included amongst the 90+ sample files that have been successfully analysed using this application, as well as many that are far more complex than these

For example: the following file has 35 fields with 7 'subarrays' 2 levels deep. The analysis creates 8 tables which are populated using a transform function created automatically.

`[{
	"cardType": "product",
	"webUrl": "http://www.examplestore.com/listing/36226783/green-leather-shoes",
	"offerPrice": 7.99,
	"currency": "USD",
	"originalPrice": 17.99,
	"shippingCost": 1.5,
	"description": "Primaryoffer",
	"availability": "InStock",
	"quantity": 15,
	"saleStartDate": "2014-06-01T00:00:00.000+0000",
	"saleEndDate": "2014-06-24T00:00:00.000+0000",
	"expirationDate": "2014-07-13T00:00:00.000+0000",
	"geographicAvailability": "US",
	"weight": 17.0,
	"weightUnits": "oz",
	"product":[{
		"name": "Greenleathershoes",
		"merchant": "ExampleStore",
		"brand": "Shoemaster",
		"productDescription": "Brilliant,colorful shoes made from recycled materials.",
		"colors": [{
			"swatchUrl": "https://www.examplestore.com/swatches/mint.jpg",	
			"displayName": "Mint",
			"mappingColor": "green",
			"value": "RGB(62,180,137)"		
		}],
		"images": ["http://img.examplestore.com/02/wer4554/il5d9184iqm9.jpg", "http://img.examplestore.com/017/fgh/il57w9.jpg", "https://img.examplestore.com/020rjt/24554/il570d143us0.jpg", "https://img.examplestore.com/0166f54/il570xg9087gc.jpg"],
		"rating": 8.0,
		"ratingScale": 10.0,
		"ratingCount": 12,
		"relatedItems": ["http://www.examplestore.com/listing/36226783/green-leather-shoes", "http://www.examplestore.com/listing/16362355/maroon-checkered-shoes", "http://www.examplestore.com/listing/13245522/pink-nylon-shoes"],
		"referencedItems": ["http://www.examplestore.com/listing/45637734/blue-leather-shoes", "http://www.examplestore.com/listing/88833589/yellow-leather-shoes"],
		"sizes": ["S", "M", "L"],
		"options": ["exampleoptiona", "exampleoptionb", "exampleoptionc"]],
		"model": "KICKN-GRL-17",
		"gender": "unisex",
		"appLinkIos": "jump://VerticalA/x123",
		"appLinkAndroid": "market://search?q=pub:examplestore"
	}
}]`

The analysis summary for the above file is in the attached report:
[rptJSONFileStructure.pdf](https://github.com/VBA-tools/VBA-JSON/files/1580070/rptJSONFileStructure.pdf)

For further details, see http://www.mendipdatasystems.co.uk/json-analyse-transform/4594138310.
The latest version is available for purchase with full source code at a reasonable price.
Earlier versions with fewer features can also be downloaded for free.

An earlier version of the app is also available at https://www.access-programmers.co.uk/forums/showthread.php?t=295789

**Comment by timhall** [comment]
I was able to get this working with the following:

```vb
' Top-level object (ryanclouse)
Dim Json As String
Json = "{""latitude"": 52.24593734741211,""longitude"": -0.891636312007904,""addresses"":[""10 Watkin Terrace, , , , , Northampton, Northamptonshire"",""12 Watkin Terrace, , , , , Northampton, Northamptonshire""]}"

Dim ParsedA As Dictionary
Set ParsedA = JsonConverter.ParseJson(Json)

Dim Address As Variant
For Each Address In ParsedA("addresses")
    Debug.Print Address
Next Address

' Top-level array
Json = "[""10 Watkin Terrace, , , , , Northampton, Northamptonshire"",""12 Watkin Terrace, , , , , Northampton, Northamptonshire""]"

Dim ParsedB As Collection
Set ParsedB = JsonConverter.ParseJson(Json)

For Each Address In ParsedB
    Debug.Print Address
Next Address


' Top-level array of objects (dymeng)
Json = "[ { ""customer"": { ""first_name"": ""blah"", ""last_name"": ""blah"" } }, { ""customer"": { ""first_name"": ""blah"", ""last_name"": ""blah"" } }, { ""customer"": { ""first_name"": ""blah"", ""last_name"": ""blah"" } } ]"

Dim ParsedC As Collection
Set ParsedC = JsonConverter.ParseJson(Json)

Dim Customer As Dictionary
For Each Customer In ParsedC
    Debug.Print Customer("customer")("first_name") & " " & Customer("customer")("last_name")
Next Customer
```
