### ISSUE TITLE
Run-time error '453'

### ISSUE THREAD

**Issue by tjkoch** [VBA-tools/VBA-JSON#72]
I get the below error when using Excel 2016 32bit and Windows 10. Can anyone confirm this is working for them with same setup?

Error: Can't find DLL entry point RtlMoveMemory in kernel32

**Comment by timhall** [comment]
Hi @tjkoch sorry for the delay in checking this out, after searching around this seems most likely a deep issue and I think the best route would be to provide a means to disable it (also there seems to potentially be some performance issue with it in some situations). I've got some plans for v2 of VBA-JSON and I'll make sure this is included. In the meantime, not sure I can help.
