### ISSUE TITLE
Not parsing JSON strings

### ISSUE THREAD

**Issue by jcamp** [VBA-tools/VBA-JSON#74]
Trying to parse strings returned like this:

{"success":true,"terms":"https:\/\/currencylayer.com\/terms","privacy":"https:\/\/currencylayer.com\/privacy","historical":true,"date":"2015-08-31","timestamp":1440979199,"source":"USD","quotes":{"USDKRW":1181.945007}}

The array returned after parsing does not contain any values? What could be the problem?

The array (called Item) that receives the content:
![image](https://user-images.githubusercontent.com/148007/32286746-6b01cd7e-bf26-11e7-8fa0-4bfcbb11c6be.png)

Any help appreciated - love the code!

---

Should add I am using your "Dictionary v1.4.1" as final = MAC Excel....

**Comment by ridders52** [comment]
Hi
I've only just found this thread
If you are still in need of a solution, please read my comment on this related thread:
[https://github.com/VBA-tools/VBA-JSON/issues/70](url)

**Comment by jcamp** [comment]
No all ok now - cheers
