### ISSUE TITLE
Handle Pretty-formatted JSON

### ISSUE THREAD

**Issue by s2t2** [VBA-tools/VBA-JSON#75]
Hi, first of all, thanks for this library. It works very well on normal JSON and it really improves the capabilities of Excel VBA.

However, I ran into errors when trying to use it to parse a pretty-formatted JSON output like [this one](https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo).

Do you have any advice on how I could use the library to parse pretty-formatted JSON like that?

**Comment by timhall** [comment]
I was able to get it to parse ok with the following:

```vb
Dim Client As New WebClient
Dim Response As WebResponse

Set Response = Client.GetJson("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo")

Dim Json As String
Dim Parsed As Dictionary
Dim Series As Dictionary
Dim Day As Variant

Json = Response.Content
Set Parsed = JsonConverter.ParseJson(Json)

' Built-in to VBA-Web:
' Set Parsed = Response.Data

Set Series = Parsed("Time Series (Daily)")
For Each Day In Series.Keys
    Debug.Print Day & " - High: " & Series(Day)("2. high")
Next Day
```
