### ISSUE TITLE
VBA  438: Object Doesn't support this property or method

### ISSUE THREAD

**Issue by stubbly** [VBA-tools/VBA-JSON#76]
trying to get JSON working with VBA and I keep getting the above error whenever I try to reference the JSON field.  Also I think I am trying to reference a nested JSON so assume I have to parse the second data item?  Is this normal in JSON?

Set Json = JsonConverter.ParseJson(response)
result = Json("akey")

it fails on any key at the Json("akey") execution

Anyone else seen this problem know how to resolve?

**Comment by stubbly** [comment]
I get the same error with the example code provided in docs README

**Comment by timhall** [comment]
Could you post the json that you are trying parse?

**Comment by stubbly** [comment]
{
   "code": 200,
   "data":    {
      "sessionToken": "xxxxxxxxxx",
      "sessionExpiration": "2017-11-14T19:28:00.152Z",
      "accountId": 62308,
      "userId": 127778,
      "userName": "xxxxxx",
      "firstName": "xxxx",
      "lastName": "xxxx",
      "accountName": "Eden Group",
      "termsAndConditionsUrl": "",
      "daysToKeepSubmittedForms": -1,
      "dataPostURLOverride": "",
      "dataPostSecurityMethod": "",
      "dataPostUserName": "",
      "dataPostPassword": "",
      "isWhiteLabel": true,
      "whiteLabelAccountId": 0,
      "roles": ["Admin"],
      "globalLists": [],
      "defaultDateFormat": "dd/MM/yyyy",
      "lookupLists": [],
      "formsMenuName": null,
      "formsMenuHidden": false,
      "libraryMenuName": null,
      "libraryMenuHidden": true,
      "inBoxMenuName": null,
      "inBoxMenuHidden": false,
      "inProgressMenuName": null,
      "syncMenuName": null,
      "syncMenuHidden": false,
      "submittedMenuName": null,
      "submittedMenuHidden": false,
      "kioskMenuHidden": true
   }
}

**Comment by stubbly** [comment]
This also fails (the JSON is from the example in the README but I've removed linefeeds and added "")

Set Json = JsonConverter.ParseJson("{""timestamp"": 1465843806,""base"": ""CAD"",""rates"": {""AED"": 2.87198141,""AFN"": 54.21812828,""ALL"": 95.86530071,""AMD"": 374.48549935,""ANG"": 1.39861507}}")

**Comment by stubbly** [comment]
At debug it happens on the step into of the Json("XXX"), so it's not like it is failing within the module.

**Comment by timhall** [comment]
Did you import or copy/paste Dictionary? There is some metadata that allows it to access by key as the default property that might have been removed if you didn’t import it. Try importing VBA-Dictionary/Dictionary.cls or removing it and adding a reference to Microsoft Scripting

**Comment by stubbly** [comment]
That sorted it for a basic test... must have cut and pasted rather than imported.  Off to try something more complex. Thanks for help. Appreciated.
