### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by stubbly** [VBA-tools/VBA-JSON#77]
Another issue now.....  the following JSON parsed outputs Code and Data only.  But the Data element is empty.  Is it too long for the VBA JSON code?  Is there a way to handle nested JSON (assuming that is what I am dealing with) Thanks (see below)

**Comment by stubbly** [comment]
{
"code": 200,
"data": {
"sessionToken": "xxxxxxxxxx",
"sessionExpiration": "2017-11-14T19:28:00.152Z",
"accountId": 12345,
"userId": 12345,
"userName": "xxxxxx",
"firstName": "xxxx",
"lastName": "xxxx",
"accountName": "xxxxxxx",
"termsAndConditionsUrl": "",
"daysToKeepSubmittedForms": -1,
"dataPostURLOverride": "",
"dataPostSecurityMethod": "",
"dataPostUserName": "",
"dataPostPassword": "",
"isWhiteLabel": true,
"whiteLabelAccountId": 0,
"roles": ["Admin"],
"globalLists": [],
"defaultDateFormat": "dd/MM/yyyy",
"lookupLists": [],
"formsMenuName": null,
"formsMenuHidden": false,
"libraryMenuName": null,
"libraryMenuHidden": true,
"inBoxMenuName": null,
"inBoxMenuHidden": false,
"inProgressMenuName": null,
"syncMenuName": null,
"syncMenuHidden": false,
"submittedMenuName": null,
"submittedMenuHidden": false,
"kioskMenuHidden": true
}
}

**Comment by stubbly** [comment]
![json](https://user-images.githubusercontent.com/33664769/32843530-f1892eb8-ca17-11e7-9148-936aa7f72b7e.jpg)

**Comment by timhall** [comment]
The explorer only shows one level deep and only the keys of items in Dictionaries. The items should be inside data if parsing completed, you can access them as follows:

```vb
Dim Role As String
Role = Json("data")("roles")(1) ' = "Admin"

' Objects -> Dictionaries, by key
' Arrays -> Collections, by index (1-based)
```

**Comment by stubbly** [comment]
That does it... thanks for help.
