### ISSUE TITLE
Complex JSON

### ISSUE THREAD

**Issue by stubbly** [VBA-tools/VBA-JSON#78]
Last issue hopefully!
I need to submit the following 

{
"formId": 1234,
"name": "xxxxxxxxxxxxxxxx",
"autoCreateUsers": false,
"recipients": [
	{
	"firstName": "xxxxx",
	"lastName": "xxxxx",
	"email": "xxx@xxxxx"
	},
],
"message": "xccccccccccc",
"dispatchEmailSubject": "ccccccccccccccccc",
"dispatchEmailMessage": "xxxxxxxxxxxxxxxx",
"mergeFields": [
	{
	"fieldKey": "CustName",
	"value": "xxxxxxxxxxxx"
	},
	{
	"fieldKey": "ID",
	"value": 12345
	},
	{
	"fieldKey": "CustAddress1",
	"value": "xxxxxxxxxxxxxxxxxx"
	},
]
}

Basic constructs all work fine e.g. 
        JsonSend("autoCreateUsers") = "false"

The two fields recipients & mergeFields wont add in the exact way that is required i.e. [ {field1 info } {field2 info} {filed 3 info} ]

I think it should be
        JsonSend("recipients")(1)("firstName") = "xxxxx"
        JsonSend("recipients")(1)("lastName") = "xxxxx"
etc but it fails.

Even a simple multi level fails:
JsonSend("recipients")("firstName") = "xxxxx"

Any ideas?
thanks

**Comment by timhall** [comment]
Generating JSON is a little trickier. You'll need to initialize Dictionaries and Collections manually before adding items to them. Something like the following should work:

```vb
Dim JsonSend As New Dictionary
JsonSend("autoCreateUsers") = False

' 1. Create recipients array
Set JsonSend("recipients") = New Collection

' 2. Add empty object as first item in recipients
JsonSend("recipients").Add New Dictionary

' 3. Set values on added object
JsonSend("recipients")(1)("firstName") = "xxxxx"

' Alternatively, create objects/collections separately and then add to json
Dim Recipients As New Collection
Dim Recipient1 As New Dictionary

Recipient1("firstName") = "xxxxx"
Recipients.Add Recipient1
Set JsonSend("recipients") = Recipients
```

**Comment by stubbly** [comment]
Fabulous I have a fully working system... need to learn more about Dictionaries and Collections but thanks very much for the help.  You have been great Tim.
