### ISSUE TITLE
ParseJson hangs/extremely slow in new Excel version

### ISSUE THREAD

**Issue by VillainGuy** [VBA-tools/VBA-JSON#79]
With the newest version of Excel (64-bit), ParseJson now takes up to 5+ minutes to handle .json files compared to only seconds in the past.

**Comment by VillainGuy** [comment]
Appears to have been an issue with Version 1710, now resolved in 1711. 
I believe it was append and/or VBA.Mid that was causing the issue, as I could shave off time by trimming my .json down.  
During the issue a 30,000+ character .json would take over 90s to parse, but now that it is resolved it is down to under a second!  
Going to close the issue, but I do wonder if there's any better way to handle the parsing instead of character by character?

**Comment by timhall** [comment]
Sweet! There are probably more efficient ways, but I'm glad it's back down to a reasonable time.

**Comment by VillainGuy** [comment]
Thanks for the reply!  
One thing I was experimenting with while I was trying to shave off time was using InStr and InStrRev.
You'd have to use place markers, but something along the lines of 
'Dim Quote1, Quote2 as Long'
'Quote1 =InStr(1, jsonstring, Chr(34))' to find a quote, then 
'Quote2 = InStr(Quote1, jsonstring, Chr(34))' to find the closing quote, and then 
'Mid(jsonstring, Quote1, Quote2 - Quote1)' to get what's in between.
Not sure if it'd be faster or not, but I might test it as I had already started the code for it :).
