### ISSUE TITLE
Json parse - key & value misplaced

### ISSUE THREAD

**Issue by bfbuckler** [VBA-tools/VBA-JSON#80]
The json format is below but when parsed the key name is parsed as the value and key is called item x:

[
    {
        "id": "genesis-vision",
        "name": "Genesis Vision",
        "symbol": "GVT",
        "rank": "172",
        "price_usd": "6.80006",
        "price_btc": "0.00067909",
        "24h_volume_usd": "6267960.0",
        "market_cap_usd": "25342334.0",
        "available_supply": "3726781.0",
        "total_supply": "4436644.0",
        "max_supply": null,
        "percent_change_1h": "-5.85",
        "percent_change_24h": "21.73",
        "percent_change_7d": "137.2",
        "last_updated": "1512023972"
    }
]

Code:

Sub test()

 Dim httpObject As Object
 Set httpObject = CreateObject("MSXML2.XMLHTTP")
  sURL = "https://api.coinmarketcap.com/v1/ticker/genesis-vision/"
 sRequest = sURL
 httpObject.Open "GET", sRequest, False
 httpObject.Send
 sGetResult = httpObject.ResponseText

 Dim Json As Object
 Set Json = JsonConverter.ParseJson(sGetResult)
End Sub

but the result is:

![capture](https://user-images.githubusercontent.com/34122452/33419641-47bd0054-d579-11e7-92e7-2f3b06083157.JPG)

**Comment by timhall** [comment]
That's just how VBA displays dictionaries in the Locals Window, it shows what keys are available. Here's how you can access them:

```vb
' Access first price
' (note: Collections are 1-based)
Json(1)("price_usd")

' Iterate through each item
Dim Item As Dictionary
For Each Item In Json
  Debug.Print Item("symbol") & ": $" & Item("price_usd")
Next Item
```

**Comment by bfbuckler** [comment]
Works perfect, thank you
