### ISSUE TITLE
Code running in vba Excel

### ISSUE THREAD

**Issue by madsbe** [VBA-tools/VBA-JSON#81]
Hi, I'm trying to make this code work in Excel, but I can't seem to manage the output.
Anyone who has an example of how to get the data comming from the Parse into a Spreadsheet?
Any help is highly appriciated

Marc

**Comment by mithunmanohar** [comment]
Check out https://youtu.be/CFFLRmHsEAs

**Comment by timhall** [comment]
@mithunmanohar Thanks for the link, looks great. Closing.
