### ISSUE TITLE
Extract Json Result

### ISSUE THREAD

**Issue by haukep85** [VBA-tools/VBA-JSON#84]
Hey all,
maybe someone have a smart solution or hint for my issue:

I have the result already in VBA. The Json Result are 3 modules.

`
    "modules": [
        {
            "localId": "598d58882e00008b1174fa0a",
            "templateRefId": "m0001599",
            "description": {
                "title": "Stop",
                "keySentence": "
                "keyHighlights": [
                ],
                "keyCategories": [],
                "shortDescription": 
                  }
                ]
            },
            "exchangeableModule": true,
            "exchangeableModuleDescription": "Vorprogramm",
            "startDate": "2018-11-03",
            "startConnections": [],
            "startLocation": {
                "refId": "DXB",
                "name": "Flughafen Dubai, Dubai (DXB)",
                "city": "Dubai",
                "country": "Vereinigte Arabische Emirate",
                "iataCode": "DXB",
                "coordinate": {
                    "lat": 25.252778,
                    "lng": 55.364444
                }
            },
            "endDate": "2018-11-06",
            "endLocation": {
                "refId": "Colombo-Sri-Lanka",
                "name": "Colombo",
                "shortName": "Colombo",
                "coordinate": {
                    "lat": 6.9270786,
                    "lng": 79.861243
                },
                "airports": [],
                "aliases": [],
                "realm": {
                    "countryCode": "LK",
                    "country": "Sri Lanka",
                    "state": "Western Province",
                    "county": "Colombo",
                    "town": "Colombo"
                }
            },
            "legs": [
                {
                    "markerIndex": 0,
                    "localId": "5a2ec9db250000cc0189fbac",
                    "connections": [
                        {
                            "jsonClass": "TransitCO",
                            "localId": "5a882b0b26000039187fd0bb",
                            "startLocation": {
                                "coordinate": {
                                    "lat": 25.2531745,
                                    "lng": 55.365672800000084
                                },
                                "address": {
                                    "realm": {
                                        "countryCode": "AE",
                                        "state": "Dubai",
                                        "county": "",
                                        "town": "Dubai",
                                        "district": "",
                                        "neighborhood": ""
                                    },
                                    "postalCode": "",
                                    "street": "",
                                    "streetNumber": "",
                                    "formattedAddress": "Dubai - United Arab Emirates"
                                },
                                "name": "Dubai"
                            },
                            "endLocation": {
                                "coordinate": {
                                    "lat": 25.2048493,
                                    "lng": 55.270782800000006
                                },
                                "address": {
                                    "realm": {
                                        "countryCode": "AE",
                                        "state": "Dubai",
                                        "county": "",
                                        "town": "Dubai",
                                        "district": "",
                                        "neighborhood": ""
                                    },
                                    "postalCode": "",
                                    "street": "",
                                    "streetNumber": "",
                                    "formattedAddress": "Dubai - United Arab Emirates"
                                },
                                "name": "Dubai"
                            },
                            "namePart1": "Dubai Flughafen",
                            "namePart2": "Dubai Hotels",
                            "startDateTime": "2018-11-03T20:30:00.000+04:00",
                            "endDateTime": "2018-11-03T21:01:00.000+04:00",
                            "transferType": "Road",
                            "transferTypesText": "Transfer",`

Everytime "jsonClass" is = "TransitCO", then i need namePart1, namePart2 and startDateTime.

I can extract it for one modul, but not the other ones.:

`
Dim var_dmc As Object  
Dim trans As Integer  
Set var_dmc = JsonConverter.ParseJson(MyDMC.ResponseText)

     trans = 33
    For Each item In var_dmc("modules")
    dmc.Cells(trans, 2) = item("legs")(1)("connections")(1)("namePart1")
    dmc.Cells(trans, 3) = item("legs")(1)("connections")(1)("namePart2")
    dmc.Cells(trans, 4) = item("legs")(1)("connections")(1)("startDateTime")
    dmc.Cells(trans, 5) = item("legs")(1)("connections")(1)("endDateTime")
    trans = trans + 1
    Next`

Any ideas?

Kind regards,
Chris

**Comment by timhall** [comment]
I'm not exactly sure what you're asking for but the following may work:

```vb
Dim Module As Dictionary
Dim Leg As Dictionary
Dim Connection As Dictionary
Dim RowIndex As Long

RowIndex = 33
For Each Module In Parsed("modules")
    For Each Leg In Module("legs")
        For Each Connection In Leg("connections")
            If Leg("jsonClass") = "TransitCO" Then
                dmc.Cells(RowIndex, 2) = Connection("namePart1")
                dmc.Cells(RowIndex, 3) = Connection("namePart2")
                dmc.Cells(RowIndex, 4) = Connection("startDateTime")
                dmc.Cells(RowIndex, 5) = Connection("endDateTime")
                RowIndex = RowIndex + 1
            End If
        Next Connection
    Next Leg
Next Module
```
