### ISSUE TITLE
works on Excel 2016 32bit but not 64bit

### ISSUE THREAD

**Issue by kohleth** [VBA-tools/VBA-JSON#86]
Hi there,
 
I have a macro that parses a JSON using this library.
The JsonConvertor works fine.
However, when i try to access an element `Dict(key)`, it works on my 32bit Excel 2016 (on my 64bit laptop), but when I do the same on the 64bit Excel 2016 (on a 64bit laptop), I get the error

Run-time error '458': Variable uses an Automation type not supported in Visual Basic.

Note that the JsonConvertor works (as in doesn't throw any error) in both version of Excel, it is just the accessing items that causes the problem.

I tried stepping into the code line by line with my 32bit and 64bit excel side by side. The difference is the line `dict_pDictionary.item(key)` in `Public Property Get item(key As Variant) As Variant`, where the the working 32bit returns a Variant/Object/dictionary whereas the 64bit returns a Variant/Integer with the value `<Internal error>`

So maybe this is a VBA-Dictionary issue? I am not sure.

**Comment by timhall** [comment]
Hi @kohleth it's actually an issue in https://github.com/VBA-tools/VBA-UTC, I'll try to fix it shortly (related: https://github.com/VBA-tools/VBA-Web/issues/248)

**Comment by timhall** [comment]
Fixed in v2.2.4
