### ISSUE TITLE
XML error -1072896682 when Import JsonConverter.bas

### ISSUE THREAD

**Issue by iray8298** [VBA-tools/VBA-JSON#87]
URL not supplied 

Excel 2016

Windows 7 X64

![image](https://user-images.githubusercontent.com/35577134/37560111-6c01618e-2a2a-11e8-93b1-e5c24978679c.png)

**Comment by timhall** [comment]
Found a few details here, [What is parseError code -107289676...](https://social.msdn.microsoft.com/Forums/en-US/8927c0be-c091-47c9-b5b3-a3957ded8624/what-is-parseerror-code-1072896760-from-msxml2domdocument?forum=xmlandnetfx):

> Error code -1072896760 (HEX C00CE508) is actually MSG_E_BADCHARDATA, which means "An invalid character was found in text content". So, you have an invalid character in your XML document.

I'm assuming there is a bad character somewhere in the underlying XML that's throwing the error. If you can trace it back to an issue in VBA-JSON I'm happy to reopen and look at this again.
