### ISSUE TITLE
ParseJSON and Collections of Dictonaries

### ISSUE THREAD

**Issue by timhall** [VBA-tools/VBA-JSON#9]
From @MaarekElets

When encountering a json array of objects (ex `[{key1:value, key2:value}, {key1:value, key2:value}]`). The parser returns a collection of just the key values. This is due to the `json_ParseArray` function not checking for { before passing int `json_ParseValue`. I believe this could be resolved with a change to the `json_ParseArray` function (changes comment marked):

```VB.net
Private Function json_ParseArray(json_String As String, ByRef json_Index As Long, Optional json_ConvertLargeNumbersToString As Boolean = True) As Collection
    Set json_ParseArray = New Collection
    Dim json_Object As Dictionary 'New object for Dictionary handling

    json_SkipSpaces json_String, json_Index
    If VBA.Mid$(json_String, json_Index, 1) <> "[" Then
        Err.Raise 10001, "JSONConverter", json_ParseErrorMessage(json_String, json_Index, "Expecting '['")
    Else
        json_Index = json_Index + 1

        Do
            json_SkipSpaces json_String, json_Index
            If VBA.Mid$(json_String, json_Index, 1) = "]" Then
                json_Index = json_Index + 1
                Exit Function
            ElseIf VBA.Mid$(json_String, json_Index, 1) = "," Then
                json_Index = json_Index + 1
                json_SkipSpaces json_String, json_Index
            End If

            'This check to see if the value is the start of an object
            If VBA.Mid$(json_String, json_Index, 1) = "{" Then
                Set json_Object = json_ParseObject(json_String, json_Index, json_ConvertLargeNumbersToString)
                json_ParseArray.Add json_Object
            Else
                json_ParseArray.Add json_ParseValue(json_String, json_Index, json_ConvertLargeNumbersToString)
            End If

        Loop
    End If
End Function
```

VBA-Web: https://github.com/VBA-tools/VBA-Web/issues/78

**Comment by timhall** [comment]
`json_ParseValue` works with values, arrays, and objects so it _should_ work in this case, but I'll add some tests and see if I can identify the bug. Have you tried your fix?

**Comment by MaarekElets** [comment]
My fix works; however I may have been too quick on thinking I found the issue. Turns out my API was camelCasing my properties so they may have been their all along. I'm going to remove my code change and see if it still functions. If so then it was a non-issue (and apologies for raising it as such).

**Comment by timhall** [comment]
No problem! Glad to hear you're using it and I'll add some tests just to be safe.

**Comment by MaarekElets** [comment]
Thanks, it's an amazingly useful tool and has saved me a ton of time and effort.

**Comment by timhall** [comment]
A good test for objects inside arrays exists, closing
