### ISSUE TITLE
Return Count of JSON candidates

### ISSUE THREAD

**Issue by bbulla24** [VBA-tools/VBA-JSON#92]
Hi,

Your JSON parser works great for a webservice I created that returns addresses from a GIS database, but I was wondering if there is a way to get the count of all of the 'address candidates' that are in the JSON response?  Perhaps it is already there and I have missed it??

Here is a typical response my webservice returns.  It would be nice just do a json.Count (or similar) to know how many addresses were returned (in the case below, 19).

{"spatialReference":{"wkid":26917,"latestWkid":26917},"candidates":[{"address":"1669 Nash Road Condominium, Clarington","location":{"x":677723.68326790119,"y":4864528.5515185883},"score":95.879999999999995,"attributes":{"Score":95.879999999999995,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"","City":"Clarington"},"extent":{"xmin":677523.68326790119,"ymin":4864328.5515185883,"xmax":677923.68326790119,"ymax":4864728.5515185883}},{"address":"1669 Nash Road, Condominium G-18, Clarington","location":{"x":677710.06050503487,"y":4864523.5129624596},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-18","City":"Clarington"},"extent":{"xmin":677510.06050503487,"ymin":4864323.5129624596,"xmax":677910.06050503487,"ymax":4864723.5129624596}},{"address":"1669 Nash Road, Condominium G-17, Clarington","location":{"x":677711.18018417433,"y":4864519.9673118507},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-17","City":"Clarington"},"extent":{"xmin":677511.18018417433,"ymin":4864319.9673118507,"xmax":677911.18018417433,"ymax":4864719.9673118507}},{"address":"1669 Nash Road, Condominium G-16, Clarington","location":{"x":677712.48647650424,"y":4864516.2350480519},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-16","City":"Clarington"},"extent":{"xmin":677512.48647650424,"ymin":4864316.2350480519,"xmax":677912.48647650424,"ymax":4864716.2350480519}},{"address":"1669 Nash Road, Condominium G-15, Clarington","location":{"x":677713.97938202368,"y":4864512.5027842531},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-15","City":"Clarington"},"extent":{"xmin":677513.97938202368,"ymin":4864312.5027842531,"xmax":677913.97938202368,"ymax":4864712.5027842531}},{"address":"1669 Nash Road, Condominium G-14, Clarington","location":{"x":677715.09906116361,"y":4864509.1437468333},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-14","City":"Clarington"},"extent":{"xmin":677515.09906116361,"ymin":4864309.1437468333,"xmax":677915.09906116361,"ymax":4864709.1437468333}},{"address":"1669 Nash Road, Condominium G-13, Clarington","location":{"x":677716.59196668305,"y":4864505.9713226045},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-13","City":"Clarington"},"extent":{"xmin":677516.59196668305,"ymin":4864305.9713226045,"xmax":677916.59196668305,"ymax":4864705.9713226045}},{"address":"1669 Nash Road, Condominium G-12, Clarington","location":{"x":677721.4439096218,"y":4864507.6508413143},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-12","City":"Clarington"},"extent":{"xmin":677521.4439096218,"ymin":4864307.6508413143,"xmax":677921.4439096218,"ymax":4864707.6508413143}},{"address":"1669 Nash Road, Condominium G-11, Clarington","location":{"x":677725.36278661061,"y":4864509.1437468333},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-11","City":"Clarington"},"extent":{"xmin":677525.36278661061,"ymin":4864309.1437468333,"xmax":677925.36278661061,"ymax":4864709.1437468333}},{"address":"1669 Nash Road, Condominium G-10, Clarington","location":{"x":677729.6548899794,"y":4864510.4500391632},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-10","City":"Clarington"},"extent":{"xmin":677529.6548899794,"ymin":4864310.4500391632,"xmax":677929.6548899794,"ymax":4864710.4500391632}},{"address":"1669 Nash Road, Condominium G-9, Clarington","location":{"x":677734.13360653818,"y":4864512.1295578731},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-9","City":"Clarington"},"extent":{"xmin":677534.13360653818,"ymin":4864312.1295578731,"xmax":677934.13360653818,"ymax":4864712.1295578731}},{"address":"1669 Nash Road, Condominium G-8, Clarington","location":{"x":677738.05248352746,"y":4864513.8090765821},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-8","City":"Clarington"},"extent":{"xmin":677538.05248352746,"ymin":4864313.8090765821,"xmax":677938.05248352746,"ymax":4864713.8090765821}},{"address":"1669 Nash Road, Condominium G-1, Clarington","location":{"x":677738.79893628694,"y":4864534.709753857},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-1","City":"Clarington"},"extent":{"xmin":677538.79893628694,"ymin":4864334.709753857,"xmax":677938.79893628694,"ymax":4864734.709753857}},{"address":"1669 Nash Road, Condominium G-2, Clarington","location":{"x":677740.10522861686,"y":4864530.9774900582},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-2","City":"Clarington"},"extent":{"xmin":677540.10522861686,"ymin":4864330.9774900582,"xmax":677940.10522861686,"ymax":4864730.9774900582}},{"address":"1669 Nash Road, Condominium G-3, Clarington","location":{"x":677741.41152094631,"y":4864527.4318394484},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-3","City":"Clarington"},"extent":{"xmin":677541.41152094631,"ymin":4864327.4318394484,"xmax":677941.41152094631,"ymax":4864727.4318394484}},{"address":"1669 Nash Road, Condominium G-7, Clarington","location":{"x":677742.15797370626,"y":4864515.301982102},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-7","City":"Clarington"},"extent":{"xmin":677542.15797370626,"ymin":4864315.301982102,"xmax":677942.15797370626,"ymax":4864715.301982102}},{"address":"1669 Nash Road, Condominium G-4, Clarington","location":{"x":677742.53120008623,"y":4864524.0728020296},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-4","City":"Clarington"},"extent":{"xmin":677542.53120008623,"ymin":4864324.0728020296,"xmax":677942.53120008623,"ymax":4864724.0728020296}},{"address":"1669 Nash Road, Condominium G-5, Clarington","location":{"x":677743.83749241568,"y":4864520.7137646107},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-5","City":"Clarington"},"extent":{"xmin":677543.83749241568,"ymin":4864320.7137646107,"xmax":677943.83749241568,"ymax":4864720.7137646107}},{"address":"1669 Nash Road, Condominium G-6, Clarington","location":{"x":677745.51701112557,"y":4864516.4216612419},"score":91.760000000000005,"attributes":{"Score":91.760000000000005,"AddNum":"1669","StName":"Nash","StType":"Road","StDir":"","SubAddType":"Condominium","SubAddUnit":"G-6","City":"Clarington"},"extent":{"xmin":677545.51701112557,"ymin":4864316.4216612419,"xmax":677945.51701112557,"ymax":4864716.4216612419}}]}

**Comment by carl-miranda** [comment]
You can try jsonObjects("candidates").Count, where jsonObjects are returned objects from calling JsonConverter.ParseJson(jsontext).

**Comment by bbulla24** [comment]
Amazing!!  I was trying that before but the intellisense never activated on the .count so I didn't even bother to test it.

Thanks for responding!!
