### ISSUE TITLE
ParseJson suddenly very slow

### ISSUE THREAD

**Issue by rachid-adf** [VBA-tools/VBA-JSON#96]
Hello !!!
 
the sub ParseJson suddenly became very slow in one computer only (a recent one i7-7 Gen), I didn't change anything in the code, 3 minutes for a little json,

after test I noticed that this row of code takes a long time to execute (a couple of second for each iteration) :

  _**json_CopyMemory ByVal json_UnsignedAdd(StrPtr(json_buffer),  json_BufferPosition), ByVal StrPtr(json_Append),  json_AppendLength**_

 do you have an idea where this comes from?

**Comment by counterpoint1** [comment]
I believe I now have the exact same problem. It broke my process dependent on this converter.  It must be one of these latest Excel 2017 updates that broke this.   This is on Windows side.

My json is about 80k large, and when i interrupt the loop it seems stuck in the subroutine:
'Private Sub json_BufferAppend(ByRef json_buffer As String, _
                              ByRef json_Append As Variant, _
                              ByRef json_BufferPosition As Long, _
                              ByRef json_BufferLength As Long)'

**Comment by rachid-adf** [comment]
@Locke  try with this, it works for me
https://github.com/PGS62/VBA-JSON/blob/0a88ffd8fd4a73ba58ba6b95cd463271062d0180/JsonConverter.bas

**Comment by hlalibe** [comment]
Hi guys,
struggling here, not so familiar with Git
i've downloaded and installed the new JsonConverter.bas file
but now i have an error message on Dim cSA As New clsStringAppend -> Compile error - user defined type not defined.
Any guidance appreciated

**Comment by rachid-adf** [comment]
@hlalibe you have just to add the class clsStringAppend.cls in your project

**Comment by rachid-adf** [comment]
@hlalibe in your project insert a new **Class Module** from menu and copy the code into

**Comment by hlalibe** [comment]
ok got it,
but i had to comment out these 4 first lines to avoid compiling errors
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END

**Comment by marcelmueller1978** [comment]
@rachid-adf
Thanks a lot for your solution!

**Comment by duncanelliot** [comment]
Hi There,

@rachid-adf @Locke Could you take a look at the link and let me know whether mine is the same problem as yours... I can't quite decide.

https://github.com/VBA-tools/VBA-Web/issues/345

Thanks,

Duncan

**Comment by iamanubhavp** [comment]
Hey @rachid-adf, I've been getting "Compile error: Expected: end of statement", while running the class module code you've shared above.
Could you please help me on this ?

**Comment by iamanubhavp** [comment]
Hey @rachid-adf, I've been getting "Compile error: Expected: end of statement", while running the class module code you've shared above.
Could you please help me on this ?
![Compile Error](https://user-images.githubusercontent.com/42218172/55936012-ac578000-5c52-11e9-8b41-abe5cf7f9c60.PNG)

**Comment by rachid-adf** [comment]
Hi @iamanubhavp, juste delete all text before  Option Explicit, and also delete the rows numbers

**Comment by iamanubhavp** [comment]
@rachid-adf, I already tried doing that. I think the issue here is with the way I'm running this code. I think I need to import the code .BAS & .cls file. 
Is that correct ?

**Comment by timhall** [comment]
@iamanubhavp What version of VBA-JSON are you using? The `clsStringAppend` approach is part of v2.3.0 and later (you can download the latest version here: https://github.com/VBA-tools/VBA-JSON/releases/latest

**Comment by iamanubhavp** [comment]
Thanks @timhall , I resolved it by importing .bas & .cls files rather than  copy/pasting the code into the modules.
