### ISSUE TITLE
parameters and variable have no purpose?

### ISSUE THREAD

**Issue by ashleedawg** [VBA-tools/VBA-JSON#97]
I'm not sure whether this would be considered an issue in itself, but perhaps is the cause of other issues?

It seems that, in `Private Function json_BufferToString` (below), the parameter `ByVal json_BufferLength As Long` is required but not referenced anywhere within the function.  The function is called several times elsewhere in the module, with the variable supplied.  If it doesn't have a "purpose", why is in even listed?

Also, in `Private Function json_StringIsLargeNumber`, declared variable `json_Index As Long` is unused.

Is this unnecessary overhead?

```
Private Function json_BufferToString(ByRef json_buffer As String, ByVal json_BufferPosition As Long) As String
#If Mac Then
	json_BufferToString = json_buffer
#Else
	If json_BufferPosition > 0 Then
		json_BufferToString = VBA.Left$(json_buffer, json_BufferPosition \ 2)
	End If
#End If
End Function
```

**Comment by timhall** [comment]
Thanks for the code review @ashleedawg, I'll get those cleaned up.
