### ISSUE TITLE
Vba Runtime Error 14 Out Of String Space

### ISSUE THREAD

**Issue by merce333** [VBA-tools/VBA-JSON#98]
Hello. I am running into the same error mentioned by @madmatthemad and @CatalinRadoi here: [https://github.com/VBA-tools/VBA-JSON/issues/50](url) 
But my error does occur on the same line @timhall suspected here [https://github.com/VBA-tools/VBA-JSON/blob/b6108e88f956f36397fe82cd805233898e734a73/JsonConverter.bas#L159](url)

JsonString = VBA.Replace(VBA.Replace(VBA.Replace(JsonString, VBA.vbCr, ""), VBA.vbLf, ""), VBA.vbTab, "")

Hitting the same endpoint with Postman shows successful Status 200 OK in 15.8 seconds, with a size of 15.36MB.
Has anyone successfully worked around such an issue by chunking the response? Thank you for your input.

**Comment by madmatthemad** [comment]
Hi Merce333,

I confess I did get around it in the end.   I installed Excel on my 64bit 32Gb RAM gaming PC, and it flew through with no problems.   Previously, I was running Excel in Parallels Desktop on my mac, and that limits the amount of RAM available to Excel to only 2Gb I believe...   

Not a great deal of help if you are limited by the hardware you're running on though I'm afraid.

**Comment by timhall** [comment]
Closing, will track this in #90. Will look into this in an upcoming batch of fixes.

**Comment by merce333** [comment]
The great Tim Hall commented on a thread I started! Thanks, for everything you do, Tim - I'm a big fan!
