### ISSUE TITLE
Run-time error '458' in Windows Excel 2016 64bit

### ISSUE THREAD

**Issue by Buffelstoot** [VBA-tools/VBA-JSON#99]
I get an error when trying to retrieve values. (See the colored line on the screenshot)

![image](https://user-images.githubusercontent.com/39762683/40713846-4b126b60-6401-11e8-9dfc-41ab79147b39.png)

The code works fine in Excel 2016 32bit.
I am using Windows, not a Mac and I've allready installed the latest version: VBA-JSON v2.2.4

My Json string looks like this:

`{
    "rows": [
        {
            "object": {
                "id": "123",
                "label": "TEST",
                "entityId": 1
            },
            "values": [
                "12345678",
                "TEST"
            ]
        }
    ]
}`

Am I doing something wrong?

**Comment by timhall** [comment]
I'm not entirely sure, but it may be from lack of a type on `json_Row`. If you explicitly define `Dim json_Row As Dictionary` do you still get the error?

**Comment by Buffelstoot** [comment]
Hi Tim,

I didn't see that one coming. :) That was the problem.
Thank you for the solution!
